// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	externalRef0 "github.com/kubev2v/migration-planner/api/v1alpha1"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get agent status
	// (GET /agent)
	GetAgentStatus(c *gin.Context)
	// Change agent mode
	// (POST /agent)
	SetAgentMode(c *gin.Context)
	// List detected applications running on VMs
	// (GET /applications)
	GetApplications(c *gin.Context)
	// Get latest cluster utilization by cluster ID
	// (GET /clusters/{cluster_id}/utilization)
	GetClusterUtilization(c *gin.Context, clusterId string)
	// Stop collection
	// (DELETE /collector)
	StopCollector(c *gin.Context)
	// Get collector status
	// (GET /collector)
	GetCollectorStatus(c *gin.Context)
	// Start inventory collection
	// (POST /collector)
	StartCollector(c *gin.Context)
	// Delete stored credentials
	// (DELETE /credentials)
	DeleteCredentials(c *gin.Context)
	// Get stored credential status
	// (GET /credentials)
	GetCredentials(c *gin.Context)
	// Store vCenter credentials
	// (PUT /credentials)
	PutCredentials(c *gin.Context)
	// Check vSphere operation capabilities
	// (GET /credentials/capabilities)
	GetCredentialCapabilities(c *gin.Context)
	// Export VM inventory and migration planning data
	// (GET /export)
	ExportInventory(c *gin.Context, params ExportInventoryParams)
	// Cancel benchmark
	// (DELETE /forecaster)
	StopForecaster(c *gin.Context)
	// Poll forecaster status
	// (GET /forecaster)
	GetForecasterStatus(c *gin.Context)
	// Start benchmark
	// (POST /forecaster)
	StartForecaster(c *gin.Context)
	// Compute pair capabilities
	// (POST /forecaster/capabilities)
	PostForecasterPairCapabilities(c *gin.Context)
	// Verify vCenter credentials and permissions
	// (PUT /forecaster/credentials)
	PutForecasterCredentials(c *gin.Context)
	// List available datastores
	// (POST /forecaster/datastores)
	GetForecasterDatastores(c *gin.Context)
	// Cancel a single pair
	// (DELETE /forecaster/pairs/{name})
	StopForecasterPair(c *gin.Context, name string)
	// List benchmark runs
	// (GET /forecaster/runs)
	GetForecasterRuns(c *gin.Context, params GetForecasterRunsParams)
	// Delete a benchmark run
	// (DELETE /forecaster/runs/{id})
	DeleteForecasterRun(c *gin.Context, id int64)
	// Get throughput statistics
	// (GET /forecaster/stats)
	GetForecasterStats(c *gin.Context, params GetForecasterStatsParams)
	// List all groups
	// (GET /groups)
	ListGroups(c *gin.Context, params ListGroupsParams)
	// Create a new group
	// (POST /groups)
	CreateGroup(c *gin.Context)
	// Delete group
	// (DELETE /groups/{id})
	DeleteGroup(c *gin.Context, id openapi_types.UUID)
	// Get group by ID with its VMs
	// (GET /groups/{id})
	GetGroup(c *gin.Context, id openapi_types.UUID, params GetGroupParams)
	// Update group
	// (PATCH /groups/{id})
	UpdateGroup(c *gin.Context, id openapi_types.UUID)
	// Stop inspector entirely
	// (DELETE /inspector)
	StopInspection(c *gin.Context)
	// Get inspector status
	// (GET /inspector)
	GetInspectorStatus(c *gin.Context, params GetInspectorStatusParams)
	// Start inspection for VMs
	// (POST /inspector)
	StartInspection(c *gin.Context)
	// Validate vCenter credentials for inspector
	// (POST /inspector/credentials)
	ValidateInspectorCredentials(c *gin.Context)
	// Get VDDK status
	// (GET /inspector/vddk)
	GetInspectorVddkStatus(c *gin.Context)
	// Upload VDDK tarball
	// (PUT /inspector/vddk)
	PutInspectorVddk(c *gin.Context)
	// Get collected inventory
	// (GET /inventory)
	GetInventory(c *gin.Context, params GetInventoryParams)
	// List all rightsizing reports
	// (GET /rightsizing)
	ListRightsizingReports(c *gin.Context)
	// Trigger rightsizing metrics collection
	// (POST /rightsizing)
	TriggerRightsizingCollection(c *gin.Context)
	// Get a specific rightsizing report with full VM metrics
	// (GET /rightsizing/{report_id})
	GetRightsizingReport(c *gin.Context, reportId string)
	// Get cluster-level utilization aggregates for a specific report
	// (GET /rightsizing/{report_id}/clusters)
	ListRightsizingReportClusters(c *gin.Context, reportId string, params ListRightsizingReportClustersParams)
	// Get utilization for a specific cluster from a specific report
	// (GET /rightsizing/{report_id}/clusters/{cluster_id})
	GetRightsizingReportCluster(c *gin.Context, reportId string, clusterId string)
	// Get agent version information
	// (GET /version)
	GetVersion(c *gin.Context)
	// Get list of VMs with filtering and pagination
	// (GET /vms)
	GetVMs(c *gin.Context, params GetVMsParams)
	// Batch update VM exclusion status
	// (POST /vms/batch-update-exclusion)
	BatchUpdateVMExclusion(c *gin.Context)
	// Get distinct filter option values for VMs
	// (GET /vms/filter-options)
	GetVMsFilterOptions(c *gin.Context)
	// Get all distinct labels in use across VMs
	// (GET /vms/labels)
	GetVMLabels(c *gin.Context)
	// Delete label from all VMs
	// (DELETE /vms/labels/{label})
	DeleteLabelGlobally(c *gin.Context, label string)
	// Modify label VM membership (add/remove label to/from VMs)
	// (PATCH /vms/labels/{label})
	UpdateLabelVMs(c *gin.Context, label string)
	// Get details about a vm
	// (GET /vms/{id})
	GetVM(c *gin.Context, id string)
	// Update VM properties
	// (PATCH /vms/{id})
	UpdateVM(c *gin.Context, id string)
	// Remove VirtualMachine from inspection queue
	// (DELETE /vms/{id}/inspection)
	RemoveVMFromInspection(c *gin.Context, id string)
	// Get utilization breakdown for a specific VM
	// (GET /vms/{id}/utilization)
	GetVMUtilization(c *gin.Context, id string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetAgentStatus operation middleware
func (siw *ServerInterfaceWrapper) GetAgentStatus(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAgentStatus(c)
}

// SetAgentMode operation middleware
func (siw *ServerInterfaceWrapper) SetAgentMode(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SetAgentMode(c)
}

// GetApplications operation middleware
func (siw *ServerInterfaceWrapper) GetApplications(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApplications(c)
}

// GetClusterUtilization operation middleware
func (siw *ServerInterfaceWrapper) GetClusterUtilization(c *gin.Context) {

	var err error

	// ------------- Path parameter "cluster_id" -------------
	var clusterId string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster_id", c.Param("cluster_id"), &clusterId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter cluster_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetClusterUtilization(c, clusterId)
}

// StopCollector operation middleware
func (siw *ServerInterfaceWrapper) StopCollector(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StopCollector(c)
}

// GetCollectorStatus operation middleware
func (siw *ServerInterfaceWrapper) GetCollectorStatus(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCollectorStatus(c)
}

// StartCollector operation middleware
func (siw *ServerInterfaceWrapper) StartCollector(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StartCollector(c)
}

// DeleteCredentials operation middleware
func (siw *ServerInterfaceWrapper) DeleteCredentials(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteCredentials(c)
}

// GetCredentials operation middleware
func (siw *ServerInterfaceWrapper) GetCredentials(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCredentials(c)
}

// PutCredentials operation middleware
func (siw *ServerInterfaceWrapper) PutCredentials(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutCredentials(c)
}

// GetCredentialCapabilities operation middleware
func (siw *ServerInterfaceWrapper) GetCredentialCapabilities(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCredentialCapabilities(c)
}

// ExportInventory operation middleware
func (siw *ServerInterfaceWrapper) ExportInventory(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ExportInventoryParams

	// ------------- Optional query parameter "scope" -------------

	err = runtime.BindQueryParameter("form", true, false, "scope", c.Request.URL.Query(), &params.Scope)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter scope: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "format" -------------

	err = runtime.BindQueryParameter("form", true, false, "format", c.Request.URL.Query(), &params.Format)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter format: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ExportInventory(c, params)
}

// StopForecaster operation middleware
func (siw *ServerInterfaceWrapper) StopForecaster(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StopForecaster(c)
}

// GetForecasterStatus operation middleware
func (siw *ServerInterfaceWrapper) GetForecasterStatus(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetForecasterStatus(c)
}

// StartForecaster operation middleware
func (siw *ServerInterfaceWrapper) StartForecaster(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StartForecaster(c)
}

// PostForecasterPairCapabilities operation middleware
func (siw *ServerInterfaceWrapper) PostForecasterPairCapabilities(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostForecasterPairCapabilities(c)
}

// PutForecasterCredentials operation middleware
func (siw *ServerInterfaceWrapper) PutForecasterCredentials(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutForecasterCredentials(c)
}

// GetForecasterDatastores operation middleware
func (siw *ServerInterfaceWrapper) GetForecasterDatastores(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetForecasterDatastores(c)
}

// StopForecasterPair operation middleware
func (siw *ServerInterfaceWrapper) StopForecasterPair(c *gin.Context) {

	var err error

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", c.Param("name"), &name, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter name: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StopForecasterPair(c, name)
}

// GetForecasterRuns operation middleware
func (siw *ServerInterfaceWrapper) GetForecasterRuns(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetForecasterRunsParams

	// ------------- Optional query parameter "pairName" -------------

	err = runtime.BindQueryParameter("form", true, false, "pairName", c.Request.URL.Query(), &params.PairName)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pairName: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetForecasterRuns(c, params)
}

// DeleteForecasterRun operation middleware
func (siw *ServerInterfaceWrapper) DeleteForecasterRun(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteForecasterRun(c, id)
}

// GetForecasterStats operation middleware
func (siw *ServerInterfaceWrapper) GetForecasterStats(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetForecasterStatsParams

	// ------------- Required query parameter "pairName" -------------

	if paramValue := c.Query("pairName"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument pairName is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "pairName", c.Request.URL.Query(), &params.PairName)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pairName: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetForecasterStats(c, params)
}

// ListGroups operation middleware
func (siw *ServerInterfaceWrapper) ListGroups(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListGroupsParams

	// ------------- Optional query parameter "byName" -------------

	err = runtime.BindQueryParameter("form", true, false, "byName", c.Request.URL.Query(), &params.ByName)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter byName: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListGroups(c, params)
}

// CreateGroup operation middleware
func (siw *ServerInterfaceWrapper) CreateGroup(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateGroup(c)
}

// DeleteGroup operation middleware
func (siw *ServerInterfaceWrapper) DeleteGroup(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteGroup(c, id)
}

// GetGroup operation middleware
func (siw *ServerInterfaceWrapper) GetGroup(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetGroupParams

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", c.Request.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sort: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetGroup(c, id, params)
}

// UpdateGroup operation middleware
func (siw *ServerInterfaceWrapper) UpdateGroup(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateGroup(c, id)
}

// StopInspection operation middleware
func (siw *ServerInterfaceWrapper) StopInspection(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StopInspection(c)
}

// GetInspectorStatus operation middleware
func (siw *ServerInterfaceWrapper) GetInspectorStatus(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetInspectorStatusParams

	// ------------- Optional query parameter "includeVddk" -------------

	err = runtime.BindQueryParameter("form", true, false, "includeVddk", c.Request.URL.Query(), &params.IncludeVddk)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter includeVddk: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetInspectorStatus(c, params)
}

// StartInspection operation middleware
func (siw *ServerInterfaceWrapper) StartInspection(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StartInspection(c)
}

// ValidateInspectorCredentials operation middleware
func (siw *ServerInterfaceWrapper) ValidateInspectorCredentials(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ValidateInspectorCredentials(c)
}

// GetInspectorVddkStatus operation middleware
func (siw *ServerInterfaceWrapper) GetInspectorVddkStatus(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetInspectorVddkStatus(c)
}

// PutInspectorVddk operation middleware
func (siw *ServerInterfaceWrapper) PutInspectorVddk(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutInspectorVddk(c)
}

// GetInventory operation middleware
func (siw *ServerInterfaceWrapper) GetInventory(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetInventoryParams

	// ------------- Optional query parameter "withAgentId" -------------

	err = runtime.BindQueryParameter("form", true, false, "withAgentId", c.Request.URL.Query(), &params.WithAgentId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter withAgentId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "group_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "group_id", c.Request.URL.Query(), &params.GroupId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter group_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetInventory(c, params)
}

// ListRightsizingReports operation middleware
func (siw *ServerInterfaceWrapper) ListRightsizingReports(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListRightsizingReports(c)
}

// TriggerRightsizingCollection operation middleware
func (siw *ServerInterfaceWrapper) TriggerRightsizingCollection(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.TriggerRightsizingCollection(c)
}

// GetRightsizingReport operation middleware
func (siw *ServerInterfaceWrapper) GetRightsizingReport(c *gin.Context) {

	var err error

	// ------------- Path parameter "report_id" -------------
	var reportId string

	err = runtime.BindStyledParameterWithOptions("simple", "report_id", c.Param("report_id"), &reportId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter report_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetRightsizingReport(c, reportId)
}

// ListRightsizingReportClusters operation middleware
func (siw *ServerInterfaceWrapper) ListRightsizingReportClusters(c *gin.Context) {

	var err error

	// ------------- Path parameter "report_id" -------------
	var reportId string

	err = runtime.BindStyledParameterWithOptions("simple", "report_id", c.Param("report_id"), &reportId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter report_id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRightsizingReportClustersParams

	// ------------- Optional query parameter "byExpression" -------------

	err = runtime.BindQueryParameter("form", true, false, "byExpression", c.Request.URL.Query(), &params.ByExpression)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter byExpression: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListRightsizingReportClusters(c, reportId, params)
}

// GetRightsizingReportCluster operation middleware
func (siw *ServerInterfaceWrapper) GetRightsizingReportCluster(c *gin.Context) {

	var err error

	// ------------- Path parameter "report_id" -------------
	var reportId string

	err = runtime.BindStyledParameterWithOptions("simple", "report_id", c.Param("report_id"), &reportId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter report_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "cluster_id" -------------
	var clusterId string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster_id", c.Param("cluster_id"), &clusterId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter cluster_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetRightsizingReportCluster(c, reportId, clusterId)
}

// GetVersion operation middleware
func (siw *ServerInterfaceWrapper) GetVersion(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVersion(c)
}

// GetVMs operation middleware
func (siw *ServerInterfaceWrapper) GetVMs(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetVMsParams

	// ------------- Optional query parameter "byExpression" -------------

	err = runtime.BindQueryParameter("form", true, false, "byExpression", c.Request.URL.Query(), &params.ByExpression)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter byExpression: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", c.Request.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sort: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVMs(c, params)
}

// BatchUpdateVMExclusion operation middleware
func (siw *ServerInterfaceWrapper) BatchUpdateVMExclusion(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.BatchUpdateVMExclusion(c)
}

// GetVMsFilterOptions operation middleware
func (siw *ServerInterfaceWrapper) GetVMsFilterOptions(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVMsFilterOptions(c)
}

// GetVMLabels operation middleware
func (siw *ServerInterfaceWrapper) GetVMLabels(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVMLabels(c)
}

// DeleteLabelGlobally operation middleware
func (siw *ServerInterfaceWrapper) DeleteLabelGlobally(c *gin.Context) {

	var err error

	// ------------- Path parameter "label" -------------
	var label string

	err = runtime.BindStyledParameterWithOptions("simple", "label", c.Param("label"), &label, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter label: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteLabelGlobally(c, label)
}

// UpdateLabelVMs operation middleware
func (siw *ServerInterfaceWrapper) UpdateLabelVMs(c *gin.Context) {

	var err error

	// ------------- Path parameter "label" -------------
	var label string

	err = runtime.BindStyledParameterWithOptions("simple", "label", c.Param("label"), &label, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter label: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateLabelVMs(c, label)
}

// GetVM operation middleware
func (siw *ServerInterfaceWrapper) GetVM(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVM(c, id)
}

// UpdateVM operation middleware
func (siw *ServerInterfaceWrapper) UpdateVM(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateVM(c, id)
}

// RemoveVMFromInspection operation middleware
func (siw *ServerInterfaceWrapper) RemoveVMFromInspection(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RemoveVMFromInspection(c, id)
}

// GetVMUtilization operation middleware
func (siw *ServerInterfaceWrapper) GetVMUtilization(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVMUtilization(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/agent", wrapper.GetAgentStatus)
	router.POST(options.BaseURL+"/agent", wrapper.SetAgentMode)
	router.GET(options.BaseURL+"/applications", wrapper.GetApplications)
	router.GET(options.BaseURL+"/clusters/:cluster_id/utilization", wrapper.GetClusterUtilization)
	router.DELETE(options.BaseURL+"/collector", wrapper.StopCollector)
	router.GET(options.BaseURL+"/collector", wrapper.GetCollectorStatus)
	router.POST(options.BaseURL+"/collector", wrapper.StartCollector)
	router.DELETE(options.BaseURL+"/credentials", wrapper.DeleteCredentials)
	router.GET(options.BaseURL+"/credentials", wrapper.GetCredentials)
	router.PUT(options.BaseURL+"/credentials", wrapper.PutCredentials)
	router.GET(options.BaseURL+"/credentials/capabilities", wrapper.GetCredentialCapabilities)
	router.GET(options.BaseURL+"/export", wrapper.ExportInventory)
	router.DELETE(options.BaseURL+"/forecaster", wrapper.StopForecaster)
	router.GET(options.BaseURL+"/forecaster", wrapper.GetForecasterStatus)
	router.POST(options.BaseURL+"/forecaster", wrapper.StartForecaster)
	router.POST(options.BaseURL+"/forecaster/capabilities", wrapper.PostForecasterPairCapabilities)
	router.PUT(options.BaseURL+"/forecaster/credentials", wrapper.PutForecasterCredentials)
	router.POST(options.BaseURL+"/forecaster/datastores", wrapper.GetForecasterDatastores)
	router.DELETE(options.BaseURL+"/forecaster/pairs/:name", wrapper.StopForecasterPair)
	router.GET(options.BaseURL+"/forecaster/runs", wrapper.GetForecasterRuns)
	router.DELETE(options.BaseURL+"/forecaster/runs/:id", wrapper.DeleteForecasterRun)
	router.GET(options.BaseURL+"/forecaster/stats", wrapper.GetForecasterStats)
	router.GET(options.BaseURL+"/groups", wrapper.ListGroups)
	router.POST(options.BaseURL+"/groups", wrapper.CreateGroup)
	router.DELETE(options.BaseURL+"/groups/:id", wrapper.DeleteGroup)
	router.GET(options.BaseURL+"/groups/:id", wrapper.GetGroup)
	router.PATCH(options.BaseURL+"/groups/:id", wrapper.UpdateGroup)
	router.DELETE(options.BaseURL+"/inspector", wrapper.StopInspection)
	router.GET(options.BaseURL+"/inspector", wrapper.GetInspectorStatus)
	router.POST(options.BaseURL+"/inspector", wrapper.StartInspection)
	router.POST(options.BaseURL+"/inspector/credentials", wrapper.ValidateInspectorCredentials)
	router.GET(options.BaseURL+"/inspector/vddk", wrapper.GetInspectorVddkStatus)
	router.PUT(options.BaseURL+"/inspector/vddk", wrapper.PutInspectorVddk)
	router.GET(options.BaseURL+"/inventory", wrapper.GetInventory)
	router.GET(options.BaseURL+"/rightsizing", wrapper.ListRightsizingReports)
	router.POST(options.BaseURL+"/rightsizing", wrapper.TriggerRightsizingCollection)
	router.GET(options.BaseURL+"/rightsizing/:report_id", wrapper.GetRightsizingReport)
	router.GET(options.BaseURL+"/rightsizing/:report_id/clusters", wrapper.ListRightsizingReportClusters)
	router.GET(options.BaseURL+"/rightsizing/:report_id/clusters/:cluster_id", wrapper.GetRightsizingReportCluster)
	router.GET(options.BaseURL+"/version", wrapper.GetVersion)
	router.GET(options.BaseURL+"/vms", wrapper.GetVMs)
	router.POST(options.BaseURL+"/vms/batch-update-exclusion", wrapper.BatchUpdateVMExclusion)
	router.GET(options.BaseURL+"/vms/filter-options", wrapper.GetVMsFilterOptions)
	router.GET(options.BaseURL+"/vms/labels", wrapper.GetVMLabels)
	router.DELETE(options.BaseURL+"/vms/labels/:label", wrapper.DeleteLabelGlobally)
	router.PATCH(options.BaseURL+"/vms/labels/:label", wrapper.UpdateLabelVMs)
	router.GET(options.BaseURL+"/vms/:id", wrapper.GetVM)
	router.PATCH(options.BaseURL+"/vms/:id", wrapper.UpdateVM)
	router.DELETE(options.BaseURL+"/vms/:id/inspection", wrapper.RemoveVMFromInspection)
	router.GET(options.BaseURL+"/vms/:id/utilization", wrapper.GetVMUtilization)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x97XLcOJLgqyDqdqKlWKr0Ybtn7A3/kCXbrZguW6evvri2z4MiUVVYkQAHAEuq6XPE",
	"vsNdxD7Qvsk+yQUSAAmSIIslleyevfnTbbtAIJFIJPI7fxvFPMs5I0zJ0avfRjJekAzDH4/nhKkJT8gF",
	"+WtBpNL/lgueE6EogREZT4j+P2FFNnr16yjmjJFYkWQUjRIqq79+jkZqlZPRq5FUgrL5KBrd73Gc072Y",
	"J2RO2B65VwLvKTyHiaeUJXrYq5Egfy2oIEnEGeGz1+WUqDb/169fo3KohgQgq1bl038lsRp9jcymLhVW",
	"hWzvJ+ZM8pR8sRNTzvS/JkTGgubmr6OTQgjCFLJjUTUWSTNtVOKjBmM06sHH12hEhOAisF41P4xA/s+B",
	"adyZ1Ge5wmJOFNI/ohkXSC0IwhoVHrSbnZ7+am+JBcOZRt6vPmY10Zx4szV+Oq1NHjy6KHQWwfPM85TG",
	"WP/+M5XqgsicM0naZ4urgfB3qkgGf/gnQWajV6P/tl9dhH17C/a92T8uiVhScqcXtVBgIfBq1IS/ttAa",
	"kMtJW+DWju+39jFrtAd/WGYnvGDK+40yReZEmB8ftPebydpdAzzRqE6cDhaz8Bpc3EzaWKDJJptvgEQ1",
	"6cHQ0MpvsIoX13mCFXl7H6eFpJx1Mzo6FwAkDE1I0r5h5STABghSHEmi4LLhNEU3E1nd1innKcHMnMhZ",
	"0j7w0c0EnZ1KPUkBII6i6tDaV56yM/PjYeOUNmezGWWvD6OELklU4rLFXQ3QUQAtQUwTFi8yLG4vChbg",
	"uYJgRZJjwPqMiwyr0auR3vOeokBTrf0mVN5e0r+R99MwlSeFgeqSxPVJeTFNvRlZkU3NFx289y0w3IxI",
	"iecE0RlSCyoRVcTMj2aYpsDgWiAawi1Xpkz9+Lwa58FaThbeSkbUggeorcQpMiNQIUmCdsh4Po7QMvvC",
	"sKJLshsCLcdUfOjiHrkg+WkdfY2HhGYEyVy/gJzpR/gWwQlqdGCWIIFZwjM0o2mKdipMHSLO0pWGZ8Bp",
	"SCL1RTobikPJCxGTU6ywVFyEN6bgAVwzZiF4MV/khZpMczmIdEIspwLfQ3YbyjZMPjXUqLxO0i1AI+8S",
	"hS7gCc7xlKZUrToFHzfC/r0pFqUpiZW5IX1Pxsfcgl+tqNefcUFiLBV56ASUyfzhADTOqNqNP3ENyjYS",
	"m3P4+AqiPC30TO8IVoUI4TQR8i3D09Q9JTNcpGr0aoZTSaLGnftlQdSCCHR6cYl2Tqkm2GmhZeALYogK",
	"XcYLkhQpEbuISkTMxFbQoxLFBprgA5QIkMlqUIw+cNZ8zV+N9PK4UDwzV7omS1YrOGnyXZGmK3RsxgOT",
	"PMdCUdz81wlmBU5HkVkzJBgvcA1TIcwsL/MFEQT9dIx2fqLzBTpeYppaCujFCdor9xQDbIJIhYWS+sXW",
	"LE4WYkmXlM3RgkslEZ7przD8DR6AQpAgYvWdxnNy+oCDvjSfwoFvdp5fu2nxWtGU/q18a1qaz4wmhMUB",
	"3UEzKBTzJQGYqpEoJyImTOl/3TnYOzw42I1QjNO4SPXZIizR8uT8eu+O0PlC/4ObI/gKZPieZpp0Dg8O",
	"QKQxfzsIvA9xXnzBy3kb0mML48n5NSqq7QYA3QYIGb5vgzAxc3wjEPKXL9ogvHyhFm49mn4LbGQk6z+Q",
	"jGRcrL4BFL1n8s2gGHQs3wCa5qtl701FOxUhV4dYbaFCaeQziOB75x7VS808PT2qjgP4FdkXmHI2RieC",
	"JBohOJUIC4I4DMWplrZzQZaUFzJdIRCQErSkGJ1fX6H9uPpsrMWshjQTExFY/fztZI8wrQol6OQY6UF0",
	"prVPgqYFS1ISFpelvOMi8PgsTwjTb0E5wjsr799aM8pbml+lAaXv8pbm6OrnyxpkSyLMH2v2Hu+dKUTa",
	"Ddv1xc8+WIWgIYgKSYTTqcPzlCOigNLdSw1BeXOQvnW3IM6mBq8gfBPCZ7mIkz0EwcmqMrgZk5WjOvhL",
	"joWs/TPIImaJYeauxh7Nfy/swsEfT3xoOkZ4IAZHnJdw900AmwkOeGt22OQMFoXBmw2qxXvBi7zTPNIw",
	"VtUP9aO70XM9R8N8meH7nwmbq8Xo1YuDgwdbiXlGFclytYoyfP/6xcEB0OWMplbnqEP0Dv4dkftcGFUN",
	"7dxpfXVK0BKnNNHSy24duMODo+eG15b/8niTtrG1aIhheoA5fA3fG9RRmad4hexFrIH3pMAdtE1AFgaL",
	"4g7CsSy6iwus41xGs/AeiClJOZsjxbfNxKIRHHy3ghE3nin7Hjn1RxBVCEYSDfU4LJb7yNMb9wB2q4ew",
	"WLNYNG4dlbdnYQPpTBCiVeCYqtX7N2HT0gKL5A4LchzHJNVqM0kmfOlbRrxHRms7ZwH8nAFWZpQIxGeA",
	"CtCL7kAbA10lcRvQPBwrhbWqOopGrEhTrdaMXilRkA5HRtphpOKKxzy9gh9+C70IoD+d8RMttcyLysLW",
	"Zzy4DH+lHziucLoOn6oLmiVhiXnt+u3V8Gt7sdZpljNGjgS6D7OBLIfVXko7JQrTdL2RqEEJTO9K0hjx",
	"2SzlOEH+eEMdNXKYYkkSrWGb3SBZ5DkXyrd0V56pfLVnp9WsTP99FI1EkmlkLHkatBvU/RURwA8onA60",
	"Cmu8Dx7MMD4lSxqHcPPh+Bgl8COi5YWRJfcocfKDRFMc31I2Rz9ff5C9Rv/m7jodQvYyHOuBoSt8SgRd",
	"al4meIY8SM9OtQA+o/djdIkzeBoLrbVgJpHU/5AvVpLGOEV2BQSwjNHxVBJmPB8f3l2CVTjlely5TzkO",
	"y3EwzaTz3tsBN+V9aojPJ5dnJTHBR84g/uHt1fH5eYTOry/eRuj0/UnQMO4ucNv6YQhW/452bibvLiO9",
	"sQjd3PA0Qh+vfnp7sRsUjAMPpr3kHi2WdNZ7Kc8xFe0rqZltj8T19vJ/UMOQ9epIcZRTBiQ3Lf0Hio/R",
	"2QxpCUqRJHKWrZhnGWf6kylXC+/oNBuXxEiZddNZ8FDDL/K1JGIvITOq30yArbRt5XqjIepoG/kbx29M",
	"oRWD6XrqA66AoLN83UzhA15v5g+eM0mJIj/jKUnfp3yq0dnjyp7NjJDfZjTAjjSzvZlIpBZYoQVO4MRT",
	"PTcSJONL32XlPWAwIoCN8mOY7w7L9iwdKCkBdZOHtv5WKpphRS4wm5MOhxOxYwzPtG5HNkeHV2/0ZvVJ",
	"tawAUyLVCZahK22f9gaX+DQ6epE9P5CfRkH2QO7zDqx3z/dj9vxl13x3XGwO4Mvs8Cg8YUgPf2ddGloA",
	"D/l16MsXP/M7Ipy7qw4F/ISmvGCJRvLLF3/wjb+acMQSLPcDXke91HWedy0FP21pKUcr50QcXr1ZJ/TV",
	"qe8raFWDvX/RSD+HGw1P6GYf0E1G97p2Jc7ylPQEh0iVJGT5UNen7+n0VvrcQ5ZElExRdtoWPM1r3Vne",
	"xKDneSbF/mtBhH5Vu4PB9C4USS4KJvtYbTmwigyQQQY73OqlkWnjSPosX+Hnv3r1ISjASZnVk7+jNc89",
	"mZNYC6IJ4gIe8j33rD8sbODNShF5pZWXABPX/4ymeoSJaQEFISmAu+mPsWV4O7kgID3WftN/AmzU7OHd",
	"AQElONewUIhnw88WEJIgydEMiwBEwxYcEoEAGwgYpYnY8477jqoFZQh7xyUK5vlVc2JMNWaX2Fp3RMGY",
	"s2daaiztmVraZFotHBrJF7of+r/kvFy7e4gHVOegixLaziEn3jY6B721++uepdz40BAQTajhC29ouLri",
	"KE8xY0FZqoc1DggCMYQSNRiQD1s/U226YFqe3hhCWONV0FOGNOWnKUmBCUm0Y13W6DBCUk8KnHU3eA0e",
	"yaubkV0NoYjKWyTp37Q8gN6/Ab7m8bQSzIPd/kCrXl5eTegfNDh5qKgWeRFeAzA2OMCyrtv1xvGFKGoA",
	"GQTftRLIDj6UCz4XRMqKF3OWrsy7ZNnMrm+Z6Nti8KUNGC86eOMlEUsak72ULElqGOQYfdTQqDtu/i4R",
	"uadSof/8t/+LwO2DdmiSkl39qFlo0Y53qqzc3+4Y/aL35LPaGWVULojUX1OJHN+M4AGVBhpr7IWHDFYc",
	"e9zZeZ4cP96U4fpM0k4V/tHNH/LkhFVM8CGsib9sq15S4Sw3h69xYHw4Wge039Vk8t6gzQf7iNrW7eF+",
	"nfx2vm+Go9PLnzXdknuQTkevRtYB/6k4OHhGXqM/vX8DtioXGPQa/ZALnvzQHd7Z0GEY/WvhMFSZ+dDO",
	"9fXZaU1wKQqaDLeVBH0/be8HhAlvfowp1nKi+XjgWXaGWfe6g2Ab/SH6ANVw/mkIOsBNchwyJLjEDf0r",
	"skpMmInPKy0pJAKw8rXQQ8OivuqTg6sJ7I7XShDVOJjXbtGHtRPla9A9GMmULQlTXKzWfXFWDvy7Ooqb",
	"iUQZVvFCvxjlHflBIkvT0SPTKW6oUAVOJ1ivQNbmU5jDMUtseuxa8PtA1B0XtyFfvX7EAjIQzojz4THz",
	"cemzYJImxCBFz40+XgaZYh7wCp0jnCQgTmAp6ZyRRL+bJo5eC4AzHAf5WYYDweeT4xNvOiQJYWi6WgsY",
	"q3DR2LPdJ1igwa6Zc6EV+QGTGt+Ic7h3zWxGoRSGoR1ZTBlRKMMSRJGTs9MLxLgCObOp2z47CvOF1nn/",
	"RKXic4EzA0auxQWwUxrHauP4scI1mu1yZFbsNKPsBqcF6bIakTz0SzOry01iv4gMJCH6/YkH9Za8OOGC",
	"9ErvJ+fXKIZBnf5lX1vJi0se3xK1dk5phw2ZtUc08ISC0t0BJpwQ/YNwMnnTnkyjxwUPUoYmb0ImivVw",
	"ZmvdbBmHjAPjlu2LvnbhyssJfAEeIvcV4qzaKNrRwF+upCLZuHQPr8ZuxUl9xd1wxlSXO10zy6EgPxjU",
	"5hK766M9Sm99t+/9jM0EDtC8EUXlubGUGpV5w9sb58XHJREnPMuoykjoLdUkrsfE5Rh0oVnSGJ3Uornh",
	"FULHacqBwUB0t0T7yDyl584dfGJv4ACDdeVW3FxrDm1Wn9w5vzOqknWWJQk1ysV5DbedmKtOBQL+BwMG",
	"bKsDJn2CNgw/zKQ3Ycdw9ded6cXxxDGJhxyt/dSdrf0rNlkVKRl2uvbdHY5CJ7QEdm2iYux9COOwQ/Sr",
	"bk4XgvWon9xZB6W8rR1fM+SnWrpNvB4CazclzEBsIlOX1afDwlJ+h5zV8XGWjAYcNUNG8LfSjhGNlkkC",
	"MhpO04+z0atf18jTSXLr3eivG1hCznxVJsxx+zjHIOVHU13L7DGa4Bw8RtbEAGgz8jChApUqlnNotyC3",
	"RpcveJiaX5/QN9sgLpAf+TzMhrOsXqCNkGC/+xKSjc5OndZhwzR7Fv6yJEIGDUg35ofGVAjndIzecYGs",
	"1Qd9Gv1pfDB+Nj74NFpr2PCgjirC6CWoUytdB4nKTwbsQ18zd/BruXojhWvAJP4XoMRbOaP/+PSg4cd9",
	"Y8+tUoh7R09kG9Og5BrggviVsiDyjSD4NuF3gfQ1nCyptBe6LyLmjqoFwgqlBEuFOCPo2H6JqF6jw6tB",
	"IcJp88lP7Jc9k3f4hNfNbHzG3dNSZm508LKsm/ys+rhniTssgHVvPP0v5sPOqZtZSw791ZL1/UXV8bdT",
	"OCoimrhiBUBNARqSkkjppKkWC4q7Ayc6qlSU8VT9bMYMi/z13WqhbXQbdpbyjqp4sVm5EBf06J59qTBL",
	"sLA1YFymsf6bmz4aFazUmYKBt8sUs47A9GUmOyNQwuHQnQU8Qrne7USjdZnDNpDfj+9f4CVBspjNaEzB",
	"SinokqakZl/09NGMSknZ/Lwa1fZjmVCLuMxTrqY0QXVYEGTn2SDot4Ewt9cQss4xFX146o/tfkewpNOU",
	"lKHdpuiErMwYxq+9Z5zZLobzieK4+6OctlIL4nEO/LXVAeqn8VShT78Lf/S54DGRAYUk7OzyrdC5/TTE",
	"YQbKgZ1ThGJ3Q+Bf0PlCSfo3yuZWoup3Yfn6wyCktxdoiGxN6jc26qAofQWZSPpndHZapVuA3I/nc0Hm",
	"IPrPBM/WYqRaZo3s297AWuw8GiffDwcDUdBfa8GMCYLvHogJvyAzR8V20hOe5YVWp23RD4gKRp9GCc8w",
	"ZXvx4dGzT6PdYBS+WzJ86U4937Jb06moDa+IU6zc2rngSQGp3Hv2i04QeipMXF5Pdowx8T/+3Qv8/cMu",
	"2kflb7vjRjmJpFaXYufgP//t/xweHKA/7I7RmQYyF0TV0utjXCibTw4qcsrvxp/YwADmrpoTddjNqAbg",
	"EJxSgo07ilTs/GF3OCjBOge/uCVkkWVYrMAvSsTezQRl+N4k8Ei0IwlBtgAAYrwRVNm/bLCwQQ0DSygd",
	"0Dq5HtA0GBY0jSfGFcJIiaKkwb07mhAYtnO3oPEC3fEiTZC9qUjRjOzh1PgWTeix3B18rgmVt+Et5YIv",
	"qX5MSPLnN3premi5sdqvHScM1bEedMSdBTUaS08AMDs6BNukC7ZA9YmNoNuYAM16W6DDzgIb61f3SO2h",
	"q4PF9ouH4S9xXoRE/iLT6y+NS7JgSiIcCy6lqwaIbCZWq5ZP0zJdW0yT1Jfbaed63lhDfjuaOtet/KB9",
	"G5x+yYYBc3E8QTuTAbCE7O9f4nAQSMDS4BM0PBCUddRM6rQ3VM9z4+H0QIkeVUwFmE7tSewkrH7M95HI",
	"OknFWH87lY8pVvHii6R/q5cG+/F51HsIORHovxdErM6JmCHBC5bsKUHzsGWtRxIyEpBJOuUzhLukIMWR",
	"jHlOTEHgJRErK5x4YlEwoWEbwcqw4Bdr9eyv7XU2g0ctKuEEdKV0SUzmrZX8IBkTJiijjXcjVEgTfqM/",
	"wamJc7WWC3uBTIZtafA371/bWOFSqUqUW5D/eHRwEHXIoguqlzJ2TPu5lq0pQ5LEnCUS7Tw7OHid4FWE",
	"Dv90cPD6jpDbCOkpX2ecqUU4WDrl/HaK49svC14I2YQmaiWjmdHojrKE3+nV4bsqJvuPRwfoNXp2gBK8",
	"kuEl9S3+siZ6VKN4amVhWUxLZ1e/quAT05qLNyFK0LgjJc8+zwPzvVKs7N0d8m6aF3tIGpl5XQeNfDlw",
	"pBHMvsQDjX+14VGJFgObWdfsqETCGqxfgBKzmTI2RAkD3uOX5itrW6EdqEiDXsNb53ToLlbkufWG+eJc",
	"OuqXJmZb+jAXxHghbN0wJySXmWH2Su24G4n2y4vekUsRinG6rjx5RmMMxgjW+U/gsa98Tt11Yby8thrK",
	"g6ai7EHGmJuJpZiACcbg6wthyfDjst9AbcmhX4UCrR1+orqcUpu+BmEd51104wJNPUocdKH6rWGGDkKp",
	"xVQqTSzWUmMEdkrkGF1Lgt6/vUL7olpq/zeafIXznhUgNqIMeCiUkdj0YA3cl0ZF6Iw0WR8vbJ9ft8W1",
	"YqU3EBYYhF4HZju8pxrpkJgRhY2pi6oFL5SPpx60QhaLEpQsjYgBKLZTUhanRaLX8BD+D/75/xX//C/J",
	"7IazufIdaPcEMFfioZFCHRJhKA4x45v1QSgd5aHAZs72zL0qo4RuJmAd/2tBBCUJmhamaAjjvuRvdws6",
	"9fjhPkpXuo7D8TgUegCHjuOys5xXK7V1TqT+7WohiFzwtK7kPGtrFVgRFq+QcuO1XpHRNKVOtZmSFWcJ",
	"MoZHyAL0ix1BkiCH9AjwIhsAwF/eUaT1RVAPbgPersld1tppFeaeuErc1TzejlxFZnO/nSvWny0zJbiD",
	"TWkeWrr6bP8jOuFMCZ4GS1gnvge1pabaQrgfZ+cE316V1e5rYLxsnea5+crY/fAtqsrkDyma25tjYRqF",
	"NKtgZpT5F/4w+kddzEeUnvSA/R0WxgxDZytjdtBLT6ApNF9qdLjoygt9SOpd8zktf4nKpT93wg11qG4m",
	"3UVZcJKEetZALCtO/IJTUKtz4GPxgLNoNqrRu85sFcsgdOZnD0DrCf52IIbIxYVQDmuA1BaVQkd5Mzkt",
	"U/3qk95SFvKcr3KwtC5NoqJL/rO1p+JE8CxCs5Tn+SpChZxGSBJBcRqVFSMGVqW6mZxap1vD4hzyo7wp",
	"pC28Z+CQsaQRogmJkMQKR4gts3CfG1dir6OShPtZv/hQmGZYpZcZTUNFXLBa2DhudDM5/TPSw5xpNvDU",
	"VVDeklVnvtgtWbmcsZXJStUPpwbeVomB5ep5pQNyCLt6xAFaoKuHxXVOhKRSEaYiRFlCcsI0NF+6/p1x",
	"Vv0UPBORZN2heCYpVCKMLvAdMsSLJjjPoYZDQgWJFfr5+gPCcUykDGeHyQUWffF+FQ6pRGYwmhJ1RwhD",
	"WZEqmqeko1lXmJbNo2keczm8/VwL9YqyWKGEKFtZsRpv0gQ2KgYa1xJlgivVchA2m5yzmAh2ghWZcxEM",
	"GKxWMWNRXA1+wFLwHg1ZJjUDN1kiqacHdZ1LOWpjhIXdiy6nxy3d3GsIzdH63oI3k47oZnsAq1CRlSUR",
	"mhG6Ic4KAfHZY3TNbhm/84/QhKviPDfJ3D981DfrB78MykkVs/1LGbN9VovZPq5itl0ZJ5hnYKKR3ajF",
	"zspbsPFLtX7jhzo4jR896Bq/OGAb/2xhX1foxNRWJokv7tfwbePlS4OCJm1F7pVprkZinmWEJc0ic4Gg",
	"88YhL7hQVuIxv0xdnYNGGP6aKPWSjuobDdOioeWeeEAIjBjk1yc4Xlj4d6D6MBeJCU8zd97o47UCL7++",
	"iJ5FR5+9m9qn9bU5Q7qO69iVTTktlYIoUUhSg8GLkDOlvea2TJsj2Bp8vYpLjpUiQkPw6dPlKNqQ76QV",
	"XwGkh0/sw9lJQAhlCbkP5Q4m5N4R74ezk16pJGAEzZfPj00xh1DdiOXzstSDqx2u12jEI95M7jQzuuI8",
	"leGaFMsf+xb5cRuLrK1V4bLSrGStkbxJmYoLMiMCKqFaEdPV5ygBNmYo2xk51B4hLLs4K3xPZtXCLy7R",
	"m/5cDvR9KB0xTe+4MOk4pkbBsHG/ULX4xTNsdn/zgav+6UNpuKMgbGsB6Vo1fL8664zeU7UqW/vZp+Mh",
	"ZmVXQe+KEuE5udoczC3kuOx0hcp2rqiCCUHttQgRJmi8IInhxiZdPCkr8uVEmIFjdFloHYAkBMTscpk3",
	"q5NyznEwtdWr79GfP9imWhvHWa2gd//NMWgj2/T3ex4CFdT6B5eLLStjKxRDS282p8x2+7qibyJ0eLB3",
	"ZP50dLD3wvzpxcE/X9E3u7WYngpxZufWefVAzL1/84iPHbK2jPDgRq9WOZGPWUhPsGaRIM1uVkqiXSHg",
	"kRcQ7Ry8vq7S7iJ0+PotlqsIHb2ekIQWWYSevf4JiyRCz1//sqCKvE95rQFw5xbzYt3hhfY38DKcnF/D",
	"BUDTAkroVKXMD/aefxrpP7zY+5P5w8u9wx/Nnw7/uPfsyPzx2dE/18qdd21jAjGRT7gTs8D6zYT28Gzv",
	"R/v7jy/2Do/sfg+PXu4dvbDDj178OGyjH2hc3vZtbnO6AkkCpENvYxZUC6Tdj/nf8y6AaTtdu9dq3Rj+",
	"1Wss7r/3gyI9Glm+oUYpHgIfwPGY/8pfECytQWdL0HH5WE7TOg4utar7UKZpvw7xynxrlXYEzh78BK2T",
	"NQcJmhtLmXrYJZgPT6m8lQNbcSxJPRXeGiBtPPgmUmpNRC1lJ4fJ8lX3xYP6gXVQcujuBUXZdkh0wOb0",
	"wD6c4CaGxpcrZ6Vw4SuN9phjNCm0TpWuELmP00LSpTWh2C6b7Vy0zV04cBJ+H9BQm88n6L4H63Z2C4Xi",
	"xSakvK9nKNi5b2mek0QjSyrIsJoSJIkCfVIUBOGUszkUeTRnBjlDQLMxz6aUmZlc4ePnBwe2drLtGvQK",
	"0Zn7kkqETQMoyOuwPS85AyAkgFoDb2eK49s7LBIJQg9W1Hbt/pf6pJDioCmmMa2ZjJiZC2noRQPu4UPv",
	"xuIRMUKSCgVMjZ+kqermJ65X/NpoY/g0NLWuGWFJ1J/1Pa+XWWo77VYq5ACoTguLKU7TTVxsWRJI7sqS",
	"F0iatCJNAGXjBjv/RkniVwtSlXp1WQ4nKRR7cB+tLQ5UjtPgBjmkGeHe3kbtXapM9bZASAM13beoQpc/",
	"HRvFUXE0LWhqiB/898Ea0PT94GktHq/PNlmgE6PHcw93Nv9meTQ+GB/sboDJCin1vQSxWzcw9qWaN4od",
	"en6vYJ3yWqHFdi84zwsU/Nwqs10BxInfxSBcu7N9I6rC2O1qCbKqI23sgZDtq+LFhq62UExqHck26aen",
	"TBc1Fd4oZyfWebUub6/6wvnwJHg5ROJ1rjEZHqU7OvG/EkQWqeqogeRGVUXxeuXL7Kz5hVNm1u8DdBg0",
	"gw5WZZDbACt4l5Oh1iHPOhqqeSejJ/IaPDS+pRkT5cpUBuziRo/e9ApkNSm+cbO0CEOtjT3TwkI1GpA2",
	"uboZo3eQVMfVgog7KklHLR8r+77VwmSySeCju3tUGkk0cS01yzmDK4bD2hoXr7OTIcnyNFjXsY0SjNzo",
	"YajwEmm/9NVuODVVGMpmbSBredHWaB8Fo7DRf/w70rQyKPu4BkxX+YNmQQWsIN185w+7/+JEUoh5ZryV",
	"JfwwKIJZ6AEooHTBk0ARrl5wGqg78ASLd5YBmLRrCzzpWXRWBAgDst3jsM/hZbi+qlMZTHMvF1el1XCS",
	"fGTVH2ezCMlCQiRVMriZrEmS8AGoCtXUJBlPLik5c+1pWy9idXaF7hK0PgSqycScKUyZU+q73sda1RhW",
	"vcih0jGAWLdMpRa6mK6yEihLAkv+4Ip9l95Tm59d/o2LfIGZ+ROizISe0WnaEXPIBZHnRJi68oNK1YPv",
	"zHmGTaH5YUF8cV4cz2aUBUMcXYJd2aNZr3d2KgM4AOWaMtuZQT+XWiBKirRRjG4ASIHa4wPbdzgEQBkZ",
	"XJahdiGVD4hx7JPjfdL0Irs2ps6kq+G3Qz83xeZrEbVVF/zO7Q1rKOLie0NBbWGbpAOrBEgP2x44+jEK",
	"AAPS0xVPicAsJm/XVWS00RbvIKm//MxLIolsNk6GKZyXlm2gjoJc4ITfNcl7BhdXKswUmmGa8qWvvHgS",
	"z4yKTC8dSowwv5hIZN+V21hrZ0o5NA8jMxpkEDOeJiGKbIV4VKWbzSebEyc0LzkLxunDXlrdKKp+J7WI",
	"a7Eg6Z++/Pgc2srsdq70ISjIvivStFZXzCzBTe1ONkcSOixsGnEz91rcyO7uK7GfLxZqY7Nm3WFtqPx2",
	"Ox31/wcceNW19Q7sUWFGXfX5DDaDDR/CT1yq9hms3f0mXc8CxNQEfqDlYBMt/QKUf7lFZT/vDBY7FxSK",
	"SnkdjR6LTrAZdHNpa1MwTdTL+P+HcudOj+N/cQtEqIXOcQYaKJ+VjS36JQ7ICiVzHDJid6VY9NgrKpNB",
	"a6EYa9HV2gxIgnaUVeQZR3GtmnhH/sPvxYIRqim5/s1ikD37081aIcEMdIKM09p8GUEf6Z2+NYtVTgRE",
	"c5sEsKL2EnTB5G/QZnn3y1IuJrPsaoZicGptS7r6cHYSLIZcunR72uxBI3/pa0pNuaVDJdXKQI9WCvmu",
	"WiHqY2PlkCq5xTVaqnORvv27MsLB3rGQcXwtQ/Ri9AyXsy1zOBfOZJF1ynCb5YN1m+B6bnnNHIcEtuMw",
	"QxgJMi9SLIYQptIvi+2gUr16vVI1PEYQLlwGrbsuuTZyu6/nHSzYtdKZlrFTk2gOxFZIE/3gLbwDM3zg",
	"yg6G1rr2n+xG7D98TN1PH2+DlFcM74Vxk3n1eI0dAygJ8m1DEs2SCAkxBUVLuim7GFbFcDfqkOrd17Z1",
	"w9OYW7YE7z1z+p1lTettN/1Vev6Oe3R+n96cD+jJWV/BZFl3ZldvIpHtCJKnOHZ9sDVizC+7PWkoT558",
	"8lAhjnE1TTG7DUlzYcEmyHG5E2BKmaYlx5SoqQXNOeb6oBihYI6Fp2ZYn2hIF7Sd1qWtMCKKWBXCZGNn",
	"eyXYe+YBpUuCUjoVGBpAtvyn7RJNXurfQ/LF6inIxC0U7loppeUm/SzRDawllBlYPq9Bo1P61nqrm07i",
	"AGYcygYzisBxhrhF7wa6WrR1tAIyrX4swoyzwohyWtq1yYh9BxGylyf2EQylaHehN4jP1kZlvyjq0Wuz",
	"4ZyWMo1pozJymDB4U1DHNeMPNPnpTRRtYR5QcF6u1jHgogSiY8CJB1vXkArkjhEmm7Sjd111jOE7EZBq",
	"QjWRvq/rtrNwfstR6gr5b1IHf6MKqJ7neLN69w+uI3+6/QrwIZ/mppjTk29WO7Zy9W5WoX3I6K7qZuuL",
	"rFfuNNN/wC84XjdVBeTWIVXVz0Pl1IfheGCp9PNAjfSuKugd5d6aT6uprebGB/DYBVwYKetKnXvXcF3d",
	"c4/uQkXQP3ckfTWTw1pMDkRxGPVmUNzd1ZuKPBQdWgJ/mZ0MKUPvCs7biYcE9VvQqyU+96S/PQkW4Afb",
	"cW17qOjIeoDFXL61XXQNmtyCUW2Xn3uzXQK1Bjpa2Ju0Opc81ijTduk6hJvcr5wIdEES9BNW6M8nlwgL",
	"ReOUoOdHz56/eHnoCTQ2Ah2ef9MD/EvVNw9km6xgVK1q/6plBIrTLwvMkjTYd7cCmPh80w/dyucCJ+Si",
	"Vi0ipHbY30mCPl4i+5ULmENelz9wCUJQvTFP26Fg08TIH7a+ULo9xlAHQXeIX20DS9gdVVpLGx1LG/tZ",
	"plAhE3R8fH428iKTR8tDoIKcMJzT0avRs/HB+Bno52oBhLBvwptf/TaamxAN7hoJniWjV6P3RMHEVkoH",
	"gRgMJ/Dx0cGBlaqUncQrybL/r9Lg2agL65QJfxnYcyimWpa+qRdm6aZQrrVynCJJxJIIqxBA3ohjE3pH",
	"JqTbmyy3Tsn63i/t3qH4pDk3ItUbnqy2u2k9v7N+NPIRtDr+9fshHUppxgvM5iTReHoeRjqUQ0TCbUGP",
	"exmQcDmbpdSwpQef3gkAYw8QCnfp3/eb9aQ6adkf95R4rb6sWRsDOHaOAX8LJmertO1Bk+BHIA2WCNXS",
	"Kj3oiDPkWhHvu5pM+79VdYa/7jcszF0YDrR809xG4IyYolK/9jd5C7dxQ1ygOWHEuAFd/NzZaTncNcfC",
	"z2Z/nB7Fh8lz8qeXB4dHJieXQhIOVgtneX5VL6Fcv3CRd8iVoe9/7TiQPn1K/vl/uwV/Pdh7ifdmn387",
	"/PHr7j8FGP7nJySznm6DAUpzuR6tpkBgDvRSC0o7AxKtwupr2UCFWGRFJ/jieaj4cu9KJn0AvG5ldTZu",
	"/1ULbBU8j3oL3J4DyJmuPFKzd8NUB3eWKQ174OFQPD8pB7bO/3mIN5Z13qXieW7Y7YP3pQHwC5l/jbrv",
	"q4Pz6V/45lIhEnVDtvXSx4EJO157hYWqn9r233sfBUJt9OgffYdzsIZJEEwf//yXU7qeTZShXPC5sK7s",
	"R5A7hvYMLkbQp3y4tPW07OraNjWAjC+JacZm+1m4eGm/IXbJLTXvnGJJxqOoQUunsIKfDT6ICXiLGBgf",
	"xwUMFIGe3h4/aGLApDS3PqnaaexcX/yMOEtXu2P0gSxNgWwuCdT0ESa+RSCXNDtGVwsIQ0lyTplCCScS",
	"uLggroZ2Dbd4jimTqmz/1cKs5lh9aN0ityqX6bkmFYIq9tL51nn7NAh+NHdrn5PH5YrAAd9YpMs+rEeI",
	"sFiscmXlUCjhpAk9QbdkFUHyAKws6+3W3H1A2HjusHHO+dARNUbH0EhMcwum0Pn1FeJLIu4EVUTaLtVk",
	"afvStkm3TRHnRYsits+3Qy3vvq2mthk5yqpEfXVcQG9HB4ffDSbbZ6QBUb806X3OBSqYIDheQCqjizd5",
	"pKAkSIjLtx6O/Vob+0oBaux2QeJbWWbR54IuaUrmtjuOflhK4pVopxROIucJ1H+ccUFirKXOXVvBIXAN",
	"0CVl85SYSH+3XKxXjyA4Ery+8zX888Tf0lPSbtncv4dOyjEuWionosLWN2SscIYlTksIUI0AgDz0yydU",
	"JzG8hZ8lkiQ1mjc8oNDiSWoeeXJ5A5XRJcpxfIvnpn0lRv/z7BxhES/okkABQTPLLCX3VNO96e9pJtVw",
	"acris1lKGUGY4XQlKTDmt/cxSUF7KqTSIgvnIf5poDzzOiL0ausnPMvwniR6kN5Tas0XdlsQbALam+tE",
	"+Qr4+5KSu90xOl5imuJyF7L6MYJofxmVra2iqlK8jNAyk5ELKo18JS1y4Yx77t5ENQtHZKsBRJ6z3Q94",
	"GZUAmPVNNBMYDP5aEMCHtRgAxCPfONCy7bas5YXKC2X14FfobzRHO9WpNw8brBz3qbxHO+bs9GannJsC",
	"97ZCEiGQ+m/wt9sBqlW8fVirzjl/g/azzixv/qZXDdjWNzReLFky5jlh91lqIJB7fDajMUl4XGSEqbHM",
	"teQPu8jSMfy/zkZKb8uUMgxbahvQ/SU1+BtO0GI93hH4eUXVQXGB6gfiPVuDGWRHdEtFiNQ+eXCyr1Bh",
	"Co0PKV7b3tKZP5dJmK9Y4mNBfhA86/muYUQQcl9qclpSqMpA5ik21krIRwYWXD2WfZrdpeK5ES6dvXNK",
	"WLzIsLgdo2Ojje55tqiCmaruEIgmllVf4W6VTy/xrgLmCdX3apXu1/SN2x5ycULQnwR6SJi6VcZdBTvv",
	"e1tLPPnpVo96XQGeat61uqgNzS7BN9FewBFzIvZyTEVpRXCRXEG5p4W3J5R4hpyRCwKrSLjU3moYO+dp",
	"GhpUGbJaMW1aXsByxeIKz5roQVJgoKBnWu4tH1iksSjHqCasG+em1uSB/kG+0BOYImeIznxNraxwpR81",
	"hggWKSXCGYVC1wUL1bgv21fbasfw3extm13YofY2T+qNnLYHNZT1pYuMEYYKlNKMKkTuY0ISN2vAOnfM",
	"THJ27b47O9027r2x0XnXvs69W+pVmLZtv1Rpc5612MtxgjKiFjwxPHtGMFQkMLn7OYnpjMbIVMrcU1jM",
	"iWoSPjLGDSifxxLI8jEhDk5RrTocKp7zlM9XKCGCLl1KGATfc3Gb0pnas1od3AXXfx594JWW5lteBEGO",
	"EAOmDS69O3KOqWhpbNu/M7VlVk/olx6W6VSDJhBd3K1IUltNQh9x5206LSmh9C097nkzBGruXltj9Am+",
	"USu031xXmihsjsxSK8qaPMuCj1AHUBKBFtb85k6ryxrhPSm+UaK6G9C1K8MMz0kG3a1uJlVMIeQmQehS",
	"nMLfdsfoxq9kyVm6ghjaJr1rREu8DBJ84dH779yqt8b0BoeDoXm0PQYP/RoNc4GZ2poF7PnBs21rI7LQ",
	"upspA9mioAhlVErK5q/Qr+UdGh/bxOFLyCysZyCMSxPD+ATsgJ+Dkfpm1vNyoRpUv4461ho1c4paq9WS",
	"e9b3ilmr0RwXaqGPxVK7LGLzwkLDYLiHKY5vZej4H8Vg4I6tgo4pTXE5EYBCztocp7KndD+wTuquxg57",
	"4WyVYftW2mdUAxRXdj1atZiqP58fjo9df8Uqt1A+8NGsSfqn1ZafWsKslvLezG/yRpYr26JUAx5JF3Tk",
	"kcSjA4xwadvzZ23QIMhb+78xnJGvfRq7URPNQ1bJpGBEr4Q6eGSnJqt+jK4Mibo3TeOYsoJUMU7UVSAy",
	"Qp8mI6lomlpH1TqdXosi66yjeoxJ8sfSwVlZD0C0Lx3lwbAkG6TeHZC03kJ39IiHQGPmQ1cb9TKZqQzp",
	"dQk9nx9kpDo3MpKdY5ARQrisaKfeVBFB+6W6MqOMysVjvQDGToGRNI4WI0U2qFkUrNsX5FgpZQld0qTA",
	"qa9dKSdxjZFrfZ2ubAavyafOHS2t4XEXhcly7KNL28saDFv+1B3245IMNqO8J+BtpV58UbBNGFuNZLbA",
	"3JrzBQhh/zeafO0LCzPxGLWDW3duFwVDZ6dhVrEmcnFttYbAAQaun4bAC0bpDwEy0HbdZD3VdrQsG9mC",
	"68fSOhXNsNbfz9iobAkY1qhUNLbe2oaZ4AfpL2dyPsfIFUIqQ1xcwafrM6R42Yu9MmIrmpU9r8gQS6Uc",
	"/ugojuZENTay/o4/5rXZvs3U7Dlwt68WghfzRV74O+wkyonRJJDbJypx+OiwGxUGRFNfVZs8GHCpecl7",
	"M2QYx7alzK2Qg3ZiLMkeZZIwSSG6RhZTczomXLzLIzhdreXnUZuuyloXaOdwD/pemsI3YXqak7DH8TCq",
	"Wo0ehnKbutOm7PaNGWdOepa21VwDyx8dRKMM39v1bS2HbmieksTh6IcmBFhSWsd0jciAyH0uCCh+W5Dk",
	"09RbPRwua7Rq2NBTxcpWK2xkhTzc7nGFjgh+cOFMQyNjXQVJWj84uWIK3+8+TlgFSBBGjNyZk/O50UDB",
	"xJ1lL1syO3+sSAKlhoZEGwSkCAPBFuNjLb66Q+S/P2JaHPIS8iMoSZMyRlPYcKCyWZ1e+hWW8aeR1pbK",
	"FJlXeqao+nF3jG4sPcJ0YKLFGYmQX0q7jMsxRl/NbSNbLjCyFfgiFOfFtcRzYsbYPwqc2T/FeXG8nMNn",
	"x0uITfMMew46LGOLNgBUq5bkPk95UhanCcbmcFEPdxne6UOqVepiZkb9j+AMtM65bQD1Ld9B2M6DnsHv",
	"+9b1vXPuIoPH3lCxTXR73n3vt6M/aCEOrr0WrM5OzeJUSQdArkWpNi8whap+J3xy+w+ut73vlI665sEt",
	"AMAtPrhPTmgGpf6TXAb6rksgO/PDFZ8M42cOnO7QhJuJRAJSY6y5/q8FMbVzg4dwXCX3GNueiWDGinRi",
	"vATCpIZsJdqA51VMNSJMUUHSVd8r38TEmgt+NrPdBikztdXKHmw3p6d/9vJl/mKT8f8Sob9kyYu/7Jqi",
	"VbbG2diPp4Ev77BEDBJr3IzjDn5vV75Jktvwg2Pr2zZLIjwp2x9AUNVxbynJjwYm7Enya9yshzHSQMxV",
	"vRGXM/I36m7Uvf6beqej0TI7S+QmEk6rdIj+Plxl4tuFRA2nkm2mIFaEt/3IJu/stZhYJtOXtNkK+AgS",
	"qIv4KEH9u42CsI+18YxLOSvSdNV5gm9wghqE/nAPuUssDCZvmvYX9glunNBSc9Ke2gbloWiW+/RBpI1m",
	"o4E74kzYUIfSVagtv2h1B7XFh+GZUViMP7EzW/9a/4tNQoH4IdMRlrDy2whh9PzgOXKbhXBgG0g8/tSd",
	"nqP3sEWhHQBt5Ti2gohqB9V7bbIiVTTHQu1roXsPAst7/KMzGqpg7xBqW68OyWHwWTJM+jCO/C2J7RpI",
	"wbvPvbd5k2owzw+fhbrMpMTGrUr04/PJGxPK+khxHLZQOy/LA1z6U+/1H5gj1ZINyzayZ2UsQHmRdk5s",
	"n+eUuLIvrMCpF1pj7uBulxioPzo2k28mBkYdPodqZcWbRaapNMrMDzJgeA7DB+NNnZWncyxxRj7O4Cj6",
	"xQ53gnrz63Vhb/zn7ioJfhxUj47jkKq5YRkrs60CF3UYNEl7BVV63VFeDZkLqKjypG9aa7Wh3pB2fRi5",
	"HUdHx8Rh8exK0PmcCL/uTlVr4mnEs/Za3ymNoXV0rvRif/0QZVBGkn8pO+YPrCTkPSEPPmZ7YLVTzogS",
	"NJatMiHemP3fDIxfrOek60lo4WRtQIcpbXR93WUaLNf93fjl23sMSaIdhaKeB+u7axRsTyj0IgIDVaTg",
	"TdXaB7QCN0ffe95l/bPN2OaJ+2odBbRB3DY1dD3sp5c/e891s3baF5qg1+gHr/DaD+Ad+phRZXIF9e0F",
	"nukwNO6MNnjrSwWeN8LvqnD0/OB7l0tb9/qESqbh+VyQOVZEfjsSd9XmUrIkaQc0zehYdw2HkHqt1N9G",
	"DO+kbLD7u6P6fxQW/M6FBQffjycv8udD1rgmbllwbXRcn7KebvfFuLFDnlJFN0tAQeeQn8b87KdZdJa+",
	"XXaM3bd9gjp3ORkauDZd1Z4aUCEJOFjNi2wqPdmk4WpkrU/PiNznh9t/Yv4RTfGPaIq/t2iKng5mPUpz",
	"GU8xwFnuXepHl1StlrfiN/AE/fZDjlp16I7n7E81f9gzPoM9aFflGG5YEX+jxxsjzc3kbTn+aVRwb7Fy",
	"qc0jJJpu8hTws5GbJOjoCryvH70iD3qR7QiigAYLsFamymPy61bAaZrz3uP52oLcNxNpHoyP+ZMX5b6Z",
	"1Jbqu0D2EXMbeOyFSKAXXayczdTMi5Y4LazcXvoLNfqqjnfdaPvZjHlSdJk1hjCacoMW9Eer9GnanFNL",
	"g4UkCMeCSxlC2P5v8P8Boa6wsfcpn2J929YINFdQGHtKUqMEZ3xJrLBornBYDTDd2/o0gEd1GHzSxyaA",
	"pF4iAOS4EKG5Q+s6JmZwup2sDBvKa6asHc66aD4AfoBYW6OCjCd0tvqOB/9UwX8OG4993QxJeLUTy9pa",
	"/juHdnDjFcSKZzTW5LP7dI8g2mHcdrWQKMMJeVzw/QSIwRIH2Bi1nCkXNEc7OEn2LctwxLMP5HkzkbsV",
	"//ptjdUFmnb1kmezpXLyoMDTb8lk6hC71PWAWlvfWVI1LA4HHNSHb88E5wKV8ZQXCmG0zNbylu96bE8Q",
	"KNTTtfehjOJm8jQS8M1kuxG8pvRNFR3hXdx9r7Boj+RhqsvfTN4JntUiEBsE8ju/te3OrY8PGQ7G/2re",
	"3bgeMWYmMGl91YAuNoDsIjYKo4TrwfRhjrUJKWzaCwm069TIZmBDnZvJBr10GmAYy/cDsxC+LVmFetKH",
	"CKtuZF7zGHzggWY3QAZ+P8xtGpenguDbhN+1zMx6HfgU5jJnV4h09Gq0j3O6vzwcff389f8FAAD//9LH",
	"Vbl/JgEA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	pathPrefix := path.Dir(pathToFile)

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(pathPrefix, "https://raw.githubusercontent.com/kubev2v/migration-planner/main/api/v1alpha1/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
