// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	externalRef0 "github.com/kubev2v/migration-planner/api/v1alpha1"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get agent status
	// (GET /agent)
	GetAgentStatus(c *gin.Context)
	// Change agent mode
	// (POST /agent)
	SetAgentMode(c *gin.Context)
	// List detected applications running on VMs
	// (GET /applications)
	GetApplications(c *gin.Context)
	// Get cluster-level utilization aggregates for the latest completed report
	// (GET /cluster_rightsizing)
	GetLatestRightsizingClusters(c *gin.Context, params GetLatestRightsizingClustersParams)
	// Get cluster-level utilization aggregates for a specific report
	// (GET /cluster_rightsizing/{report_id})
	GetRightsizingReportClusters(c *gin.Context, reportId string, params GetRightsizingReportClustersParams)
	// Get latest cluster utilization by cluster ID
	// (GET /clusters/{cluster_id}/utilization)
	GetClusterUtilization(c *gin.Context, clusterId string)
	// Stop collection
	// (DELETE /collector)
	StopCollector(c *gin.Context)
	// Get collector status
	// (GET /collector)
	GetCollectorStatus(c *gin.Context)
	// Start inventory collection
	// (POST /collector)
	StartCollector(c *gin.Context)
	// Delete stored credentials
	// (DELETE /credentials)
	DeleteCredentials(c *gin.Context)
	// Get stored credential status
	// (GET /credentials)
	GetCredentials(c *gin.Context)
	// Store vCenter credentials
	// (PUT /credentials)
	PutCredentials(c *gin.Context)
	// Check vSphere operation capabilities
	// (GET /credentials/capabilities)
	GetCredentialCapabilities(c *gin.Context)
	// Export VM inventory and migration planning data
	// (GET /export)
	ExportInventory(c *gin.Context, params ExportInventoryParams)
	// Cancel benchmark
	// (DELETE /forecaster)
	StopForecaster(c *gin.Context)
	// Poll forecaster status
	// (GET /forecaster)
	GetForecasterStatus(c *gin.Context)
	// Start benchmark
	// (POST /forecaster)
	StartForecaster(c *gin.Context)
	// Compute pair capabilities
	// (POST /forecaster/capabilities)
	PostForecasterPairCapabilities(c *gin.Context)
	// Verify vCenter credentials and permissions
	// (PUT /forecaster/credentials)
	PutForecasterCredentials(c *gin.Context)
	// List available datastores
	// (POST /forecaster/datastores)
	GetForecasterDatastores(c *gin.Context)
	// Cancel a single pair
	// (DELETE /forecaster/pairs/{name})
	StopForecasterPair(c *gin.Context, name string)
	// List benchmark runs
	// (GET /forecaster/runs)
	GetForecasterRuns(c *gin.Context, params GetForecasterRunsParams)
	// Delete a benchmark run
	// (DELETE /forecaster/runs/{id})
	DeleteForecasterRun(c *gin.Context, id int64)
	// Get throughput statistics
	// (GET /forecaster/stats)
	GetForecasterStats(c *gin.Context, params GetForecasterStatsParams)
	// List all groups
	// (GET /groups)
	ListGroups(c *gin.Context, params ListGroupsParams)
	// Create a new group
	// (POST /groups)
	CreateGroup(c *gin.Context)
	// Delete group
	// (DELETE /groups/{id})
	DeleteGroup(c *gin.Context, id openapi_types.UUID)
	// Get group by ID with its VMs
	// (GET /groups/{id})
	GetGroup(c *gin.Context, id openapi_types.UUID, params GetGroupParams)
	// Update group
	// (PATCH /groups/{id})
	UpdateGroup(c *gin.Context, id openapi_types.UUID)
	// Stop inspector entirely
	// (DELETE /inspector)
	StopInspection(c *gin.Context)
	// Get inspector status
	// (GET /inspector)
	GetInspectorStatus(c *gin.Context, params GetInspectorStatusParams)
	// Start inspection for VMs
	// (POST /inspector)
	StartInspection(c *gin.Context)
	// Validate vCenter credentials for inspector
	// (POST /inspector/credentials)
	ValidateInspectorCredentials(c *gin.Context)
	// Get VDDK status
	// (GET /inspector/vddk)
	GetInspectorVddkStatus(c *gin.Context)
	// Upload VDDK tarball
	// (PUT /inspector/vddk)
	PutInspectorVddk(c *gin.Context)
	// Get collected inventory
	// (GET /inventory)
	GetInventory(c *gin.Context, params GetInventoryParams)
	// List all rightsizing reports
	// (GET /rightsizing)
	ListRightsizingReports(c *gin.Context)
	// Trigger rightsizing metrics collection
	// (POST /rightsizing)
	TriggerRightsizingCollection(c *gin.Context)
	// Get a specific rightsizing report with full VM metrics
	// (GET /rightsizing/{report_id})
	GetRightsizingReport(c *gin.Context, reportId string)
	// Get cluster-level utilization aggregates for a specific report
	// (GET /rightsizing/{report_id}/clusters)
	ListRightsizingReportClusters(c *gin.Context, reportId string, params ListRightsizingReportClustersParams)
	// Get utilization for a specific cluster from a specific report
	// (GET /rightsizing/{report_id}/clusters/{cluster_id})
	GetRightsizingReportCluster(c *gin.Context, reportId string, clusterId string)
	// Get agent version information
	// (GET /version)
	GetVersion(c *gin.Context)
	// Get list of VMs with filtering and pagination
	// (GET /vms)
	GetVMs(c *gin.Context, params GetVMsParams)
	// Batch update VM exclusion status
	// (POST /vms/batch-update-exclusion)
	BatchUpdateVMExclusion(c *gin.Context)
	// Get distinct filter option values for VMs
	// (GET /vms/filter-options)
	GetVMsFilterOptions(c *gin.Context)
	// Get all distinct labels in use across VMs
	// (GET /vms/labels)
	GetVMLabels(c *gin.Context)
	// Delete label from all VMs
	// (DELETE /vms/labels/{label})
	DeleteLabelGlobally(c *gin.Context, label string)
	// Modify label VM membership (add/remove label to/from VMs)
	// (PATCH /vms/labels/{label})
	UpdateLabelVMs(c *gin.Context, label string)
	// Get details about a vm
	// (GET /vms/{id})
	GetVM(c *gin.Context, id string)
	// Update VM properties
	// (PATCH /vms/{id})
	UpdateVM(c *gin.Context, id string)
	// Remove VirtualMachine from inspection queue
	// (DELETE /vms/{id}/inspection)
	RemoveVMFromInspection(c *gin.Context, id string)
	// Get utilization breakdown for a specific VM
	// (GET /vms/{id}/utilization)
	GetVMUtilization(c *gin.Context, id string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetAgentStatus operation middleware
func (siw *ServerInterfaceWrapper) GetAgentStatus(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAgentStatus(c)
}

// SetAgentMode operation middleware
func (siw *ServerInterfaceWrapper) SetAgentMode(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SetAgentMode(c)
}

// GetApplications operation middleware
func (siw *ServerInterfaceWrapper) GetApplications(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApplications(c)
}

// GetLatestRightsizingClusters operation middleware
func (siw *ServerInterfaceWrapper) GetLatestRightsizingClusters(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetLatestRightsizingClustersParams

	// ------------- Optional query parameter "byExpression" -------------

	err = runtime.BindQueryParameter("form", true, false, "byExpression", c.Request.URL.Query(), &params.ByExpression)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter byExpression: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLatestRightsizingClusters(c, params)
}

// GetRightsizingReportClusters operation middleware
func (siw *ServerInterfaceWrapper) GetRightsizingReportClusters(c *gin.Context) {

	var err error

	// ------------- Path parameter "report_id" -------------
	var reportId string

	err = runtime.BindStyledParameterWithOptions("simple", "report_id", c.Param("report_id"), &reportId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter report_id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetRightsizingReportClustersParams

	// ------------- Optional query parameter "byExpression" -------------

	err = runtime.BindQueryParameter("form", true, false, "byExpression", c.Request.URL.Query(), &params.ByExpression)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter byExpression: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetRightsizingReportClusters(c, reportId, params)
}

// GetClusterUtilization operation middleware
func (siw *ServerInterfaceWrapper) GetClusterUtilization(c *gin.Context) {

	var err error

	// ------------- Path parameter "cluster_id" -------------
	var clusterId string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster_id", c.Param("cluster_id"), &clusterId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter cluster_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetClusterUtilization(c, clusterId)
}

// StopCollector operation middleware
func (siw *ServerInterfaceWrapper) StopCollector(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StopCollector(c)
}

// GetCollectorStatus operation middleware
func (siw *ServerInterfaceWrapper) GetCollectorStatus(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCollectorStatus(c)
}

// StartCollector operation middleware
func (siw *ServerInterfaceWrapper) StartCollector(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StartCollector(c)
}

// DeleteCredentials operation middleware
func (siw *ServerInterfaceWrapper) DeleteCredentials(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteCredentials(c)
}

// GetCredentials operation middleware
func (siw *ServerInterfaceWrapper) GetCredentials(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCredentials(c)
}

// PutCredentials operation middleware
func (siw *ServerInterfaceWrapper) PutCredentials(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutCredentials(c)
}

// GetCredentialCapabilities operation middleware
func (siw *ServerInterfaceWrapper) GetCredentialCapabilities(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCredentialCapabilities(c)
}

// ExportInventory operation middleware
func (siw *ServerInterfaceWrapper) ExportInventory(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ExportInventoryParams

	// ------------- Optional query parameter "scope" -------------

	err = runtime.BindQueryParameter("form", true, false, "scope", c.Request.URL.Query(), &params.Scope)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter scope: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ExportInventory(c, params)
}

// StopForecaster operation middleware
func (siw *ServerInterfaceWrapper) StopForecaster(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StopForecaster(c)
}

// GetForecasterStatus operation middleware
func (siw *ServerInterfaceWrapper) GetForecasterStatus(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetForecasterStatus(c)
}

// StartForecaster operation middleware
func (siw *ServerInterfaceWrapper) StartForecaster(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StartForecaster(c)
}

// PostForecasterPairCapabilities operation middleware
func (siw *ServerInterfaceWrapper) PostForecasterPairCapabilities(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostForecasterPairCapabilities(c)
}

// PutForecasterCredentials operation middleware
func (siw *ServerInterfaceWrapper) PutForecasterCredentials(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutForecasterCredentials(c)
}

// GetForecasterDatastores operation middleware
func (siw *ServerInterfaceWrapper) GetForecasterDatastores(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetForecasterDatastores(c)
}

// StopForecasterPair operation middleware
func (siw *ServerInterfaceWrapper) StopForecasterPair(c *gin.Context) {

	var err error

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", c.Param("name"), &name, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter name: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StopForecasterPair(c, name)
}

// GetForecasterRuns operation middleware
func (siw *ServerInterfaceWrapper) GetForecasterRuns(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetForecasterRunsParams

	// ------------- Optional query parameter "pairName" -------------

	err = runtime.BindQueryParameter("form", true, false, "pairName", c.Request.URL.Query(), &params.PairName)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pairName: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetForecasterRuns(c, params)
}

// DeleteForecasterRun operation middleware
func (siw *ServerInterfaceWrapper) DeleteForecasterRun(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteForecasterRun(c, id)
}

// GetForecasterStats operation middleware
func (siw *ServerInterfaceWrapper) GetForecasterStats(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetForecasterStatsParams

	// ------------- Required query parameter "pairName" -------------

	if paramValue := c.Query("pairName"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument pairName is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "pairName", c.Request.URL.Query(), &params.PairName)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pairName: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetForecasterStats(c, params)
}

// ListGroups operation middleware
func (siw *ServerInterfaceWrapper) ListGroups(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListGroupsParams

	// ------------- Optional query parameter "byName" -------------

	err = runtime.BindQueryParameter("form", true, false, "byName", c.Request.URL.Query(), &params.ByName)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter byName: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListGroups(c, params)
}

// CreateGroup operation middleware
func (siw *ServerInterfaceWrapper) CreateGroup(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateGroup(c)
}

// DeleteGroup operation middleware
func (siw *ServerInterfaceWrapper) DeleteGroup(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteGroup(c, id)
}

// GetGroup operation middleware
func (siw *ServerInterfaceWrapper) GetGroup(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetGroupParams

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", c.Request.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sort: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetGroup(c, id, params)
}

// UpdateGroup operation middleware
func (siw *ServerInterfaceWrapper) UpdateGroup(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateGroup(c, id)
}

// StopInspection operation middleware
func (siw *ServerInterfaceWrapper) StopInspection(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StopInspection(c)
}

// GetInspectorStatus operation middleware
func (siw *ServerInterfaceWrapper) GetInspectorStatus(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetInspectorStatusParams

	// ------------- Optional query parameter "includeVddk" -------------

	err = runtime.BindQueryParameter("form", true, false, "includeVddk", c.Request.URL.Query(), &params.IncludeVddk)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter includeVddk: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetInspectorStatus(c, params)
}

// StartInspection operation middleware
func (siw *ServerInterfaceWrapper) StartInspection(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StartInspection(c)
}

// ValidateInspectorCredentials operation middleware
func (siw *ServerInterfaceWrapper) ValidateInspectorCredentials(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ValidateInspectorCredentials(c)
}

// GetInspectorVddkStatus operation middleware
func (siw *ServerInterfaceWrapper) GetInspectorVddkStatus(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetInspectorVddkStatus(c)
}

// PutInspectorVddk operation middleware
func (siw *ServerInterfaceWrapper) PutInspectorVddk(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutInspectorVddk(c)
}

// GetInventory operation middleware
func (siw *ServerInterfaceWrapper) GetInventory(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetInventoryParams

	// ------------- Optional query parameter "withAgentId" -------------

	err = runtime.BindQueryParameter("form", true, false, "withAgentId", c.Request.URL.Query(), &params.WithAgentId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter withAgentId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "group_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "group_id", c.Request.URL.Query(), &params.GroupId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter group_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetInventory(c, params)
}

// ListRightsizingReports operation middleware
func (siw *ServerInterfaceWrapper) ListRightsizingReports(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListRightsizingReports(c)
}

// TriggerRightsizingCollection operation middleware
func (siw *ServerInterfaceWrapper) TriggerRightsizingCollection(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.TriggerRightsizingCollection(c)
}

// GetRightsizingReport operation middleware
func (siw *ServerInterfaceWrapper) GetRightsizingReport(c *gin.Context) {

	var err error

	// ------------- Path parameter "report_id" -------------
	var reportId string

	err = runtime.BindStyledParameterWithOptions("simple", "report_id", c.Param("report_id"), &reportId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter report_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetRightsizingReport(c, reportId)
}

// ListRightsizingReportClusters operation middleware
func (siw *ServerInterfaceWrapper) ListRightsizingReportClusters(c *gin.Context) {

	var err error

	// ------------- Path parameter "report_id" -------------
	var reportId string

	err = runtime.BindStyledParameterWithOptions("simple", "report_id", c.Param("report_id"), &reportId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter report_id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRightsizingReportClustersParams

	// ------------- Optional query parameter "byExpression" -------------

	err = runtime.BindQueryParameter("form", true, false, "byExpression", c.Request.URL.Query(), &params.ByExpression)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter byExpression: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListRightsizingReportClusters(c, reportId, params)
}

// GetRightsizingReportCluster operation middleware
func (siw *ServerInterfaceWrapper) GetRightsizingReportCluster(c *gin.Context) {

	var err error

	// ------------- Path parameter "report_id" -------------
	var reportId string

	err = runtime.BindStyledParameterWithOptions("simple", "report_id", c.Param("report_id"), &reportId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter report_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "cluster_id" -------------
	var clusterId string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster_id", c.Param("cluster_id"), &clusterId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter cluster_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetRightsizingReportCluster(c, reportId, clusterId)
}

// GetVersion operation middleware
func (siw *ServerInterfaceWrapper) GetVersion(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVersion(c)
}

// GetVMs operation middleware
func (siw *ServerInterfaceWrapper) GetVMs(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetVMsParams

	// ------------- Optional query parameter "byExpression" -------------

	err = runtime.BindQueryParameter("form", true, false, "byExpression", c.Request.URL.Query(), &params.ByExpression)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter byExpression: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", c.Request.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sort: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVMs(c, params)
}

// BatchUpdateVMExclusion operation middleware
func (siw *ServerInterfaceWrapper) BatchUpdateVMExclusion(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.BatchUpdateVMExclusion(c)
}

// GetVMsFilterOptions operation middleware
func (siw *ServerInterfaceWrapper) GetVMsFilterOptions(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVMsFilterOptions(c)
}

// GetVMLabels operation middleware
func (siw *ServerInterfaceWrapper) GetVMLabels(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVMLabels(c)
}

// DeleteLabelGlobally operation middleware
func (siw *ServerInterfaceWrapper) DeleteLabelGlobally(c *gin.Context) {

	var err error

	// ------------- Path parameter "label" -------------
	var label string

	err = runtime.BindStyledParameterWithOptions("simple", "label", c.Param("label"), &label, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter label: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteLabelGlobally(c, label)
}

// UpdateLabelVMs operation middleware
func (siw *ServerInterfaceWrapper) UpdateLabelVMs(c *gin.Context) {

	var err error

	// ------------- Path parameter "label" -------------
	var label string

	err = runtime.BindStyledParameterWithOptions("simple", "label", c.Param("label"), &label, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter label: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateLabelVMs(c, label)
}

// GetVM operation middleware
func (siw *ServerInterfaceWrapper) GetVM(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVM(c, id)
}

// UpdateVM operation middleware
func (siw *ServerInterfaceWrapper) UpdateVM(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateVM(c, id)
}

// RemoveVMFromInspection operation middleware
func (siw *ServerInterfaceWrapper) RemoveVMFromInspection(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RemoveVMFromInspection(c, id)
}

// GetVMUtilization operation middleware
func (siw *ServerInterfaceWrapper) GetVMUtilization(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVMUtilization(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/agent", wrapper.GetAgentStatus)
	router.POST(options.BaseURL+"/agent", wrapper.SetAgentMode)
	router.GET(options.BaseURL+"/applications", wrapper.GetApplications)
	router.GET(options.BaseURL+"/cluster_rightsizing", wrapper.GetLatestRightsizingClusters)
	router.GET(options.BaseURL+"/cluster_rightsizing/:report_id", wrapper.GetRightsizingReportClusters)
	router.GET(options.BaseURL+"/clusters/:cluster_id/utilization", wrapper.GetClusterUtilization)
	router.DELETE(options.BaseURL+"/collector", wrapper.StopCollector)
	router.GET(options.BaseURL+"/collector", wrapper.GetCollectorStatus)
	router.POST(options.BaseURL+"/collector", wrapper.StartCollector)
	router.DELETE(options.BaseURL+"/credentials", wrapper.DeleteCredentials)
	router.GET(options.BaseURL+"/credentials", wrapper.GetCredentials)
	router.PUT(options.BaseURL+"/credentials", wrapper.PutCredentials)
	router.GET(options.BaseURL+"/credentials/capabilities", wrapper.GetCredentialCapabilities)
	router.GET(options.BaseURL+"/export", wrapper.ExportInventory)
	router.DELETE(options.BaseURL+"/forecaster", wrapper.StopForecaster)
	router.GET(options.BaseURL+"/forecaster", wrapper.GetForecasterStatus)
	router.POST(options.BaseURL+"/forecaster", wrapper.StartForecaster)
	router.POST(options.BaseURL+"/forecaster/capabilities", wrapper.PostForecasterPairCapabilities)
	router.PUT(options.BaseURL+"/forecaster/credentials", wrapper.PutForecasterCredentials)
	router.POST(options.BaseURL+"/forecaster/datastores", wrapper.GetForecasterDatastores)
	router.DELETE(options.BaseURL+"/forecaster/pairs/:name", wrapper.StopForecasterPair)
	router.GET(options.BaseURL+"/forecaster/runs", wrapper.GetForecasterRuns)
	router.DELETE(options.BaseURL+"/forecaster/runs/:id", wrapper.DeleteForecasterRun)
	router.GET(options.BaseURL+"/forecaster/stats", wrapper.GetForecasterStats)
	router.GET(options.BaseURL+"/groups", wrapper.ListGroups)
	router.POST(options.BaseURL+"/groups", wrapper.CreateGroup)
	router.DELETE(options.BaseURL+"/groups/:id", wrapper.DeleteGroup)
	router.GET(options.BaseURL+"/groups/:id", wrapper.GetGroup)
	router.PATCH(options.BaseURL+"/groups/:id", wrapper.UpdateGroup)
	router.DELETE(options.BaseURL+"/inspector", wrapper.StopInspection)
	router.GET(options.BaseURL+"/inspector", wrapper.GetInspectorStatus)
	router.POST(options.BaseURL+"/inspector", wrapper.StartInspection)
	router.POST(options.BaseURL+"/inspector/credentials", wrapper.ValidateInspectorCredentials)
	router.GET(options.BaseURL+"/inspector/vddk", wrapper.GetInspectorVddkStatus)
	router.PUT(options.BaseURL+"/inspector/vddk", wrapper.PutInspectorVddk)
	router.GET(options.BaseURL+"/inventory", wrapper.GetInventory)
	router.GET(options.BaseURL+"/rightsizing", wrapper.ListRightsizingReports)
	router.POST(options.BaseURL+"/rightsizing", wrapper.TriggerRightsizingCollection)
	router.GET(options.BaseURL+"/rightsizing/:report_id", wrapper.GetRightsizingReport)
	router.GET(options.BaseURL+"/rightsizing/:report_id/clusters", wrapper.ListRightsizingReportClusters)
	router.GET(options.BaseURL+"/rightsizing/:report_id/clusters/:cluster_id", wrapper.GetRightsizingReportCluster)
	router.GET(options.BaseURL+"/version", wrapper.GetVersion)
	router.GET(options.BaseURL+"/vms", wrapper.GetVMs)
	router.POST(options.BaseURL+"/vms/batch-update-exclusion", wrapper.BatchUpdateVMExclusion)
	router.GET(options.BaseURL+"/vms/filter-options", wrapper.GetVMsFilterOptions)
	router.GET(options.BaseURL+"/vms/labels", wrapper.GetVMLabels)
	router.DELETE(options.BaseURL+"/vms/labels/:label", wrapper.DeleteLabelGlobally)
	router.PATCH(options.BaseURL+"/vms/labels/:label", wrapper.UpdateLabelVMs)
	router.GET(options.BaseURL+"/vms/:id", wrapper.GetVM)
	router.PATCH(options.BaseURL+"/vms/:id", wrapper.UpdateVM)
	router.DELETE(options.BaseURL+"/vms/:id/inspection", wrapper.RemoveVMFromInspection)
	router.GET(options.BaseURL+"/vms/:id/utilization", wrapper.GetVMUtilization)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x97XLcOJLgqyDqdqKlWOrLHz3T3vAPWbLdiumydfrqi2v7PCgSVYUVCXAAsOTqPkfs",
	"O9xF7APtm+yTXCABkCAJfpRUsnv2+s+MWwUCicxEIjORH79NYp7lnBGm5OTFbxMZL0mG4Z/HC8LUlCfk",
	"gvy9IFLpv+WC50QoSmBExhOi/5+wIpu8+GUSc8ZIrEgyiSYJldV/fowmap2TyYuJVIKyxSSafN7jOKd7",
	"MU/IgrA98lkJvKfwAiaeUZboYS8mgvy9oIIkEWeEz1+WU6La/F++fInKoRoSgKxalc/+lcRq8iUym7pU",
	"WBWyvZ+YM8lT8slOTDnTf02IjAXNzX9OTgohCFPIjkXVWCTNtFGJjxqM0aQHH1+iCRGCi8B61fwwAvk/",
	"B6ZxNKnPcoXFgiikf0RzLpBaEoQ1KjxoN6Oe/mpvhQXDmUbeLz5mNdOceLM1fjqtTR4kXRSiRZCeeZ7S",
	"GOvff6JSXRCZcyZJm7a4Ggj/TRXJ4B//JMh88mLy3w6qg3BgT8GBN/v7FRErSu70ohYKLAReT5rw1xYa",
	"ALmctAVujXy/tcms0R78YZWd8IIp7zfKFFkQYX68195vpoO7BniiSZ05HSxm4QFc3EzbWKDJJptvgEQ1",
	"68HQ0MqvsIqX13mCFXn9OU4LSTnrFnR0IQBIGJqQpH3CyklADBCkOJJEwWHDaYpuprI6rTPOU4KZochZ",
	"0ib45GaKzk6lnqQAECdRRbT2kafszPx41KDS5mI2o+zlUZTQFYlKXLakqwE6CqAliGnC4mWGxe1FwQIy",
	"VxCsSHIMWJ9zkWE1eTHRe95TFHiqtd+EyttL+it5OwtzeVIYqC5JXJ+UF7PUm5EV2cx80SF7X4PAzYiU",
	"eEEQnSO1pBJRRcz8aI5pCgKuBaJh3HJlytT3z6pxHqzlZOGtZEQteYDbSpwiMwIVkiRoh+wv9iO0yj4x",
	"rOiK7IZAyzEV77qkRy5IflpHX+MioRlBMtc3IGf6Er5FQEGNDswSJDBLeIbmNE3RToWpI8RZutbwjKCG",
	"JFIfpLOxOJS8EDE5xQpLxUV4YwouwIExS8GLxTIv1HSWy1GsExI5FfgesttQtmHyuaHG5XWWbgEaeYco",
	"dABPcI5nNKVq3an4uBH2v5tqUZqSWJkT0ndlvM8t+NWKev05FyTGUpH7TkCZzO8PQING1W78iWtQtpHY",
	"nMPHVxDlaaFnekOwKkQIp4mQrxmepe4qmeMiVZMXc5xKEjXO3M9LopZEoNOLS7RzSjXDzgqtA18Qw1To",
	"Ml6SpEiJ2EVUImImtooelSg20AQvoESATlaDYvKOs+Zt/mKil8eF4pk50jVdslrBaZNvijRdo2MzHoTk",
	"ORaK4uZfp5gVOJ1EZs2QYqwPB16Q03tg7NJ8CpjbDDFfuol6rWhKfy2FdsuEmNOEsDighOuTjmK+IgBT",
	"NRLlRMSEKf3XncO9o8PD3QjFOI2LVCMJYYlWJ+fXe3eELpb6D26OoDjN8GeaaRocHR6CbmD+6zAgaOO8",
	"+IRXizakxxbGk/NrVFTbDQC6DRAy/LkNwtTM8ZVAyH943gbhh+dq6daj6dfARkayfoJkJONi/RWg6KXJ",
	"V4NiFFm+AjRN8W/PTcU7FSNXRKy2UKE08gVE8OJwt9OlwkJ5BkkdB/ArslcZ5WwfnQiSaITgVCIsCOIw",
	"FKdabc0FWVFeyHSNQNNI0IpidH59hQ7i6rN9ra801IKYiMDq56+ne4RpmyJBJ8dID6JzbcYRNCtYkpKw",
	"3inlHRcBZXZ1QpgiApUjPFp5f2tfDLc0v0oD1tPlLc3R1U+XNchWRJh/1hwn3k1YiLQbtuuLn3ywCkFD",
	"EBWSCGechucpR0QB67WXG4KK2yjD5W5JnHMKbkH4JnjRukXcJS4ITtaV58r4fhzXwX/kWMjan+FSN0uM",
	"8xs19mj+98IuHPzxxIemY4QHYnDEeQl33wSwmeCA12aHTclgURg82aCjvxW8yDv9DA2vT52o792JXug5",
	"Gn7ADH/+ibCFWk5ePD88vLe7lWdUkSxX6yjDn18+PzwEvpzT1CrvdYjewN8R+ZwLY/OgnTtt+M0IWuGU",
	"aiM+2a0Dd3T45JmRteVfHu4bNk4LDTFMDzCHj+Fbgzoq8xSvkT2INfAeFbjDti/FwmBR3ME4VkR3SYEh",
	"yWVUdO+CmJGUswVSfNtCLJoA4dufOo08blxT9j5ydoQgqhCMJBrq/bBa7iNPb9wD2K0ewmLN9G+cOipv",
	"z8KexrkgRNuSMVXrt6/CPpolFskdFuQ4jkmq7U+STPnKdzF4l8ySS3UWwM8ZYGVOiUB8DqjQI7XoFsTY",
	"KonbgJbhWCmsbb5JNGFFmmqzZvJCiYJ0vAikHd4ernjM0yv4IeQR4QqnQ/tXXV+vCEvM7dTvqIVf24u1",
	"sF/OGDmSdSO/sTmHhV7OOCUK03TYO9KgHNO7kjRGfD5POU6QP95Qs0a+GZYkQZwhsxskizznQvku3upJ",
	"Jl/v2Wm16NH/PYkmIsk0MlY8DRrMdUd9BPADCmcj3aEa76MHM4xPyYrGIdy8Oz5GCfyIaMngsjztJU6+",
	"k2iG41vKFuin63ey19vd3F3nS4j1GxzrgaEjd0oEXWnZI3iGPEjPTrXCPKef99ElzuAqK7SVgZlEUv8h",
	"X64ljXGK7AoIYNlHxzNJmHH5v3tzCe7QlOtx5T7l/qTbwTHtPKd2wE15nhrq7snlWclM8JHzBL97fXV8",
	"fh6h8+uL1xE6fXsS9Ai7A9z2VhiG1b+jnZvpm8tIbyxCNzc8jdD7qx9fX+wGFdnABWcPuceLJZ/1Hspz",
	"TEX7SGrh2KMhvb78H9QIUL06UhzllAHLzUrHueL76GyOtMajSBIhbD6IeZZxpj+ZcbX0SKfFriRGKyz9",
	"YDFO03WQqOEb9FoSsZeQOdV3HMBW+qJyvdEQd7S92w3yGx9gJWC6ruaADzz4Sjw0U5jAw/7tIJ1JShT5",
	"Cc9I+jblM43Onjfc+dwo5W1BA+JIC9ubqURqiRVa4gQonuq5kSAZX/lvNd4FBiMC2Cg/hvnusGzP0oGS",
	"ElA3eWjrr6WiGVbkArMF6XhpIXaMkZn2vY0t0NHVK71ZTamW1T4jUp1gGTrS9hWhISU+TJ48z54dyg+T",
	"oHggn/MOrHfP93327Ieu+e642BzAH7KjJ+EJQ3bzG+vL1wpz6EGD/vD8J35HhHvnqUMBP6EZL1iikfzD",
	"8z/5zlrNOGIFLusRt6Ne6jrPu5aCn7a0lOOVcyKOrl4NPZXUue8LWEGjn72iib4ONxqe0M0+oJuM7n3T",
	"lDjLU9ITFSFVkpDVfd/8/Cc+b6WPPWxJRCkUZacvwLOUhmh5E4Nd5rkA+48FEfpW7Y6C0rtQJLkomOwT",
	"teXA6klcBgXseC+VRqYNoOjzVIWv/+rWh9dwp2VWV/6OthT3ZE5irYgmiAu4yPfctX6/9/JXa0XklTZe",
	"AkJc/xnN9AgTzAEGQlKAdNMfYyvwdnJBQHus/ab/Bdio+a+7X8JLcK5hoZDMhp8tICRBkqM5FgGIxi04",
	"5ukdNhBwIhOx55H7jqolZQh75BIF8x4Uc2JcK2aX2HpjRMGY8z9abiz9j1rbZNosHBvCFjof+n/Jebl2",
	"9xAPqM5BFyW0nUNOvG10Dnpt99c9S7nxsbEPmlHDB97wcHXEUZ5ixoK6VI9oHBH9YBglagggH7Z+odp8",
	"Mmm9zMYQuxmvgy9bSHN+mpIUhJBEO/aJGR1FSOpJQbLuBo/BA2V1M6SpoRRReYsk/VXrA+jtK5Brnkwr",
	"wTzc7Y8w6pXl1YQ+oeFRhopqkefhNQBjoyML67ZdbwBbiKNGsEHwXiuB7JBDueALQaSsZDFn6drcS1bM",
	"7Pqeib4tBm/agPOiQzZeErGiMdlLyYqkRkDuo/caGnXHzX9LRD5TqdB//tv/RfBMg3ZokpJdfalZaNGO",
	"R1VW7m93H/2s9+SL2jllVC6J1F9TiZzcjOAClQYa65yFiwxW3Peks3spcvJ4U4HrC0k7VfhHN3/o5SVs",
	"YoLPfyDwsG16SYWz3BBf48C8uWgb0H5X08l7oxXv/abT9kaPf4fJbxcHZjg6vfxJ8y35DNrp5MXEPph/",
	"KA4Pn5KX6C9vX4GvygbDoJfou1zw5LvuuMaGDcPo3wuHocrNh3aur89Oa4pLUdBkvK8k+FbTfq2A+NjN",
	"yZhirSeaj0fSsjO+uPf5BrbRH5sOUI2Xn4ahA9IkxyFHgstY0L8ia8SEhfiispJCKgArbws9NKzqqz49",
	"uJrA7nhQg6jGwbx2iz6snSgfQPdoJFO2IkxxsR764qwc+A9FipupRBlW8VLfGOUZ+U4iy9PRA/MIbqhQ",
	"BU6nWK9ABhMJDHHMEpuSXSt+74i64+I29LauL7GADoQz4t7cmPm4fLNgkibEIEXPjd5fBoViHngVOkc4",
	"SUCdwFLSBSOJvjdNALlWAOc4DsqzDAeirqfHJ950SBLC0Gw9CBircNHYs90neKDBr5lzoQ35EZOatxH3",
	"QN41sxmFUhiGdmQxY0ShDEtQRU7OTi8Q4wr0zKZt+/RJWC606P0jlYovBM4MGLlWF8BPaR5CG+THCtd4",
	"tushsxKnGWU3OC1Il9eI5KFfmulMbhL7RWQgCfHvjzxot+TFCRekV3s/Ob9GMQzqfA/2rZW8uOTxLVGD",
	"c0o7bMysPaqBpxSUzx3gwgnxPygn01ftyTR6XLAfZWj6KuSiGIaz+zl87Ht1+Qrd/aZ8xuYCB2hpVCx5",
	"bjyAxhTckCvjvHi/IuKEZxlVGQndEZp0ekxcjkEX+qjto5NaVDFIV3ScphwODkQZS3SAzBVx7p45Tyxn",
	"jXDEVs9lm1uDoc1qLjnnd8YEsI9ASUKN0nxew20n5iqq6NnGAwbHsQMmTUEbDh4WPpuIGWDpIZpeHE8d",
	"89+HtPZTR1v7n3iFqTkuo6hr75PxKHSXcWDXJtrDnocwDjtUmurkdCFYj/rR0TqovWyNfM1QlmrpNvN6",
	"CKydlLAAsZkpXd6MDs9B+R1y3rSHWegNOGoGevC30j6PJqskAd0Dp+n7+eTFLwN6YpLceif6ywYW/pmv",
	"ooclbp/kGKXUa65rmfOTKc7hJcSazoA2o+cRKlBpOriH2hbkq+oK2AgK+92n0KV7durUWRuvFwzTsxOs",
	"iJBBz8SN+aExFcI53UdvuEDWnYA+TP6yf7j/dP/ww2TQYvagjirK9FL01KptQar66VV96GtmY30pV2/k",
	"8oyYxP8CrEN70feTTw8aT+4bS7fK0uodPZVtTIP1ZIAL4lfKgshXguDbhN8F8phwsqLSnqi+UIs7qpYI",
	"K5QSLBXijKBj+yWieo0OdzmF0JnNJz+xX/ZM3vHYODSzeYzsnpYyc0EGD8vQ5GfVxz1L3GEBsnPj6X82",
	"H3ZO3UxfceivlqzvL6rI347lr5ho6tK/gZsCPCQlkdKpMy0RFHe/yHfk/ZeBOv1ixgyL/PXdaqFtdHsM",
	"VvKOqni5WQEGF03n7l2pMEuwsFU1XO6m/i83fTQpmA0C7agNskox64hQXmWyM7QhHGfbWRIhlD3bzjjx",
	"czBDEd42otsP9F7iFUGymM9pTMH9JeiKpqTmuPJipDMqJWWL82pU+4HEvOHHaHWZQ4h0NaWJ1sKCIDvP",
	"BtGkDYS5vYaQdY6p6MNTf9DwG4IlnaWkjBk2afyyso/Ng+meeSV1wYGPFCDcHz6zlez6h70MD+Zb16nx",
	"WDE1v4uHzgu6WCpJf6VsYVWS/scFXwMeBXV7gYbO02Qf4z0M6qJXkNOhf0Znp1UgPLzA4MVCkAVYp3PB",
	"s0HtsVpmQHlsb2AQOw/GybfDwUgU9GetmzFB8J2EnfILMnfmgJ30hGd5oQ1CW4cA4jXRh0nCM0zZXnz0",
	"5OmHyW4wPtotGX77O/Ve/dyazshq+KudZeLWzgVPCkiK3bNfdILQk6t/eT3dMe6w//h3LyTzT7voAJW/",
	"7e43EvOTWob/zuF//tv/OTo8RH/a3UdnGshcEFVLVI5xoWxmLrxRpvxu/wMbGVralb1fh92MagAOYQMl",
	"2Lgj3X/nT7vjQQlmjP/slpBFlmGxhhcrIvZupijDn01qhUQ7khBkU6kR441wt/5lgyniNQysIAm7Rbke",
	"0DQYFjSNJ8YVwkiJouTBvTuaEBi2c7ek8RLd8SJNkD2pSNGM7OHUvPqYoFC5O5quCZW34S3lgq+otspJ",
	"8tdXemt6aLmx2q8dFIaCPfcicWdpgsbSUwDMjg7BNu2CLZDHvxF0GzOgWW8LfNhZqmB4dY/V7rs6+Bw/",
	"eRj+FOdFSGcuMr3+yjwWFUxJhGPBpXQFypDNkWlVRWn6VmuLaZb6dDvrXM8ba9hvR3Pn0Mr32rfB6ads",
	"HDAXx1O0Mx0BS8iD/CkOP88HTHWfoeGCgAVC1Wc6Dfbqem5cnB4o0YPKUoDQqV2JnYzVj/k+FhnSVEyi",
	"faf2PsMqXn6S9Nd6taLvn0W9RMiJQP+9IGJ9TsQcCV6wZE8JmoddUz2akNGATDognyPcpQUpjmTMc2Jq",
	"lK6IWFvlxFOLgqHm2wgjhQU/Wbdhf5WkszlcalEJJ6ArpSticiKt5gdpcjBBGQe6G6FCmsAI/QlOTQSi",
	"Nf3tATK5j6UP3Nx/bWvfJbmUKLcg//nJ4WHUoYsuqV7KOALt51q3pgxJEnOWSLTz9PDwZYLXETr6y+Hh",
	"yztCbiOkp3yZcaaW4TDWlPPbGY5vPy15IWQTmqiVJmRGozvKEn6nV4fvqmjZPz85RC/R00OU4LUML6lP",
	"8aeBuD6N4pnVhWUxK59r+k0Fn5kGDt6UKEHjjmQpez2PzMRJsbJnd8y9aW7sMQk+5nYdNfKHkSONYvYp",
	"Huk9qw2PSrQY2My6ZkclEgawfgFGzGbG2BgjDGSPX+SsrBKEdqC2B3oJd52zobtEkbZKP+EN6nK6RMFP",
	"Tcy27GEuiHHj2wpMTkkuc3bskdpxJxIdlAe9I8o9FH1yXT2FGYsxGL1Vlz+By756tOmusOFlHNVQHnx7",
	"y+7ljLmZWo4JuGAMvj4Rlownl/1GKixGEzkUAuvwE9X1lNr0NQjrOO/iGxcC6HHiqAPV7w0zfBBK+qRS",
	"aWaxnhqjsFMi99G1JOjt6yt0IKqlDn6jyReg97wAtRFlIEMhwX9Twhq4L42J0BkrMRzJaa9ft8VBtdIb",
	"CAuMQq8Dsx2gUo10SMyIwsbVRdWSF8rHUw9aIb9ACUpWRsUAFNspKYvTItFreAj/Q37+fyU//0sKu/Fi",
	"rrwH2mXKzZG4b6xLh0YYiqTL+Gal2cuX5lDIKWd75lyVaRo3U/CO/70ggpIEzQpTzoFxX/O3uwWbev/+",
	"j3yuCBgH8jgUegCHyGEKx/9RzG17xdw8YH+H1dzC0Nlybh3c0ROVBq03GvXNu5Kj7pN/0pRc5S9RuXQ3",
	"V0Mxlptpd2UCnCShjgUQ+IYTv+oKFJgbeS7vQYtmmwK968yWXgtCZ372ALSPbl8PxBC7uHCvce0v2rdS",
	"iJQ309My36U+6S1loUfKdQ5OrZXJ1nEZMLYAS5wInkVonvI8X0eokLMISSIoTqMybXpkaZab6al932g4",
	"90Iu61eFtNWnDBwyljRCNCERkljhCLFVFu5y4OpMdaRTu58RZaY6w7hyB3OahioZYLW0QZ/oZnr6V6SH",
	"OS9Y4gc2NKG8JevOpIlbsnaJE2uTmkWlcaDbUgmwXD25akQiTVeHIEAL1HS3uM6JkFQqwlSEKEtITpiG",
	"5lPX3xln1U9Bmogk6w4bMplREmF0ge+QYV40xXkOicwJFSRW6KfrdwjHMZG+0u35EuUSi77YpAqHVCIz",
	"GM2IuiOEoaxIFc1T0tGqJczL5tI0l7kc33yohXpFWaxQQpQtL1aNNzHFG1XEi2tR9cGVagHLm03OWUwE",
	"O8GKLLgIBjdVq5ixKK4G32MpuI/GLJOagZsskdRzCbroUo7aGGHhlxyXAOCWbu41hOZouLPUzbQjEtMS",
	"YB2qNLAiQgtCN8QZfBBLuo+u2S3jdz4JTWgdznOT0fjde32yvvNrAZxU8aU/l/GlZ7X40uMqvtTVMoF5",
	"RmYl2I1a7Ky9BRu/VOs3fqiD0/jRg67xiwO28WcL+1C2vykwShJf3a/h28b2lrabZm1FPivTWofEPMsI",
	"S5qVlgIBsg0iL7lQVuMxv8xcsm8jZHggorbko/pGw7xoeLkn9AreoEc9oRIcLy38O1CCk4vERAKZM28q",
	"cNaqHPzyPHoaPfnondRAff+erKx0SOrYlU1NGZWCKlFIUoPBC0Yy9W0WtlaRY9gafL2GS46VIkJD8OHD",
	"5STaUO6klVwBpIcp9u7sJKCEsoR8DiUaJeSzY953Zye9WknA35Svnh2bjOZQ8vTqWZnv7Aro6jUaoV83",
	"0zstjK44T2U4MXv1fd8i329jkcGEbZdBYzVrjeRNcrUvyJwIKAdoVUyXpF4CDA4z1xczVNM7rLs4h2dP",
	"FsjSz7DuzZUsB/ru6o7wkTdcmNQBk6g7btzPVC1/9nxI3d+846p/+lDO3iQI2yAgXauGz1dnsb3PVK3L",
	"xk726riPB8+VkbqiRHjvCW0J5hZyUna2RmUzP1TBhKAAUYQIEzReksRIY5NbmpRlqXIizMB9dFloG4Ak",
	"BNTscplX65Nyzv1QHpyf5N6f69TmWhsyV62gd//VMWiDiPT3ex4CFRS8Bu+2ra1gy3RCQ1e2oMy2qLmi",
	"ryJ0dLj3xPzryeHec/Ov54f/fEVf7dbCJyrEmZ3bd4J7Yu7tqwd87JC1ZYQHN3q1zol8yEJ6goFFgjy7",
	"Wd55O534gQcQ7Ry+vK5ShCJ09PI1lusIPXk5JQktsgg9ffkjFkmEnr38eUkVeZvyWvvHzi3mxRDxQvsb",
	"eRhOzq/hAKBZAXUkqnq+h3vPPkz0P57v/cX844e9o+/Nv47+vPf0ifnn0yf/XKv527WNKYSfPeJOzALD",
	"mwnt4ene9/b375/vHT2x+z168sPek+d2+JPn34/b6Dsal6d9m9ucrUGTAO3Q25gF1QJp92P+71kXwLSd",
	"WtrrtW4M/+K1lfXv+1GP6o2MxFC3AA+B95B4zL/lLwiWm3STHoaOy4dKmhY5uNSm7n2Fpv06JCvzrZXl",
	"EDi79xU0pGuOUjQ31jL1sEtwH55SeStH1qNfkXrarnVA2tDbTbTUmopa6k4Ok+Wt7qsHdYJ1cHLo7AVV",
	"2Xb0acDndM/mcRAGAN3a1s5L4SIFGj3d9tG00DZVukbEtN9eWReKbQ3XTvvZ/AkHKOE3rwv1pnuEllGw",
	"bmeLO6jgaaJ3+xrdgZ/7luY5STSypIJklhmB3uTanhQFQTjlbAGVzgzNID0DeDbm2YwyM5Or/vns8NAW",
	"ELWtM14gOndfUomw6YICIfRl734AQgKoNfB2Zji+vcMikaD0YEVNBufuv9QnhWhyzTGNac1kxMxcSMMv",
	"GnAPH3o3Fo+IEZJUKGBq/1E6AW5Ocb3il0bvrcfhqaEOWiVTf9TnvF6Tpf1ot1ahB4CKWljMcJpu8sSW",
	"JYE8mix5jqTJ4NAMUFYvt/MHgyy7CptcLUlV79AFlJ+kkJjuPhosZFKO0+AGJaQZ4e7eRgFKqkypp0BI",
	"AzUtaKhClz8eG8NRcTQraGqYH97vg4VQ6dvR01o8Xp9tskAnRo8XHu5sqsPqyf7h/uHuBpiskFLfSxC7",
	"dQdjX1ZvozKa9+4VLNZbq8rWbojkvQIFP7fGbFesZuKX8g4XsGufiKo6bLtwpayKqRp/ICRWqni54VNb",
	"KPyvjmSbX9FTUsg2U6ecndjHq6EUqeoL94Yn4ZVDJF77BhNMXz5HJ/5XgsgiVR31WtyoqoJWr36ZnTW/",
	"cMbM8D7AhkFzaONSBjGO8IJ3PTLU2kTZh4Zq3unkkV4N7hvf0oyJcjXtAn5xY0dvegSymhbfOFlahaHW",
	"x55pZaEaDUibXt3sozeQv8TVkog7KklH3RGr+77WymSySaN5d/aoNJpo4vrKlXMGVwyHtTUOXmc7L5Ll",
	"abAIXBslGLnR41Dh5Sx+GtHSvuxYBLqWF9iKDlAw4BX9x78jzSujEj1rwHRlmjdz17GCzN6dP+3+i1NJ",
	"IbyU8VZC5v2gCCb8BqCALPFHgSKcKH4aSPF+hMW7m8S307gflRadyddhQLZLDnsdXoaLMTqTwXS4cXFV",
	"2gwnyXtW/XM+j5AsJERSJaM7Kpp4dB+AqiZITZPx9JJSMteutmEVq7M1apei9S5QuCPmTGHKnFHfdT/W",
	"CnSw6kYmwTb4qlqmMgtdTFdZtZAlgSW/M1WI0U75empTYcv/4iJfYmb+hSgzoWd0lnbEHHJB5DkRprjy",
	"qHrN8HbmXoZNteVxQXxxXhzP55QFQxxdLlPZqFSvd3YqAzgA45oyW55cX5daIUqKtFE4awRIgULFI2vY",
	"OwRAxQ5c1qx1IZX3iHHs0+N91vQiuzbmzqSr661DP1yxjYjaqnVz5/bGVdV38b2hoLawT9KBVQKkh20P",
	"HH0ZBYAB7emKp0RgFpPXQ9XjbLTFG8ifLj8Dvcp8GiFTcSXDFOildRtIWZdLnPC7JnvP4eBKhZlCc0xT",
	"vvKNF0/jmVOR6aVDiRHmFxOJ7D/lNtbamVEOHXTInAYFxJynSYgjWyEeVeFY88nmzAkV/M+Ccfqwl1ZJ",
	"9qrofy3iWixJ+pdP3z+D3gq7nSu9Cyqyb4o0rZVwMktwU2eQLZBcS0WyTSNuFl6fB9ndggDU0oXrKBro",
	"5TCw7rheLH7PiY5i4SMIXrUudB3fQ4K6anYX7IgYJsKPXKo2DQZ3v0nrnwAzNYEf6TnYxEq/AOPfmOl5",
	"Z5jXuaBQecdryPFQRIC13y1frTfA9AAuI/fvK1c73wr/i/sOQh0gjjOwHfm8rF/frytotsvIAofcz13J",
	"ET2ehsrYby0UY610WmufJGhHWROccRTXahZ3ZC78XnwPocJ7w7cNI1KR5MebwevdDHQqiLO3/Ntdk/RO",
	"n5rlOicC4rBN6lZRk+FdMPkbtKmw/VqQi6Ysm/KgGJ6jtqUXvTs7CZZcLR9je7pEQR9q6ds4TY2jw5jU",
	"anyPPRlNpOICL8i1DBHLqOd2CJI5IIUzWWSdqs9maVTdnqueI1bzYiGB7TjMEEaCLIoUizFcobRYt10K",
	"Ks9wrzIKNwFE2Zax3q7Dog147uuXBAt2rXSmVdM0dU3P9SATNOAtvAMzvOPKDoa2jPZPdiP2D+9T99P7",
	"2yDZi/Hl7m8yr2KoMf/hqoU01ZAisCJCwlN80VIKyg5YVbnOjbrreYel7RTwDM2WCe5dJs4ssnJh2OXR",
	"X0fkH7i/27fp63aPfm71FUxycmdS8ibq0I4geYpj10NVI8b8stuTvfHoORv31aAYV7MUs9uQKhXWKoIS",
	"lzvtoVQoWkpEiZparJkTrvcKrQmmJnhKvn1KDJlQtkuv8WpJJYpYFcIkMWd7Jdh7JqmSrghK6UxgaB7W",
	"enZsF5HxMubuk2ZVz9wlbqFwxzNogD+c6u0G1vKwDCwfB9DobKXBR97m22oAMw5lowVFgJwhadG7ga42",
	"SB3dPkw3D4sw4+M3epRWNW0OXx8hQm7mxF6CoczmLvQG8dnaqOzXAz1+bTZ1qprihxvhlw3w2308evMr",
	"W5hvtMHvGFD1t+8Y4He37xpSgdwxwiRhdvSHqsgYPhMBrSbUKv7bvnh2lvZuvS+6UuObVOreqEaj9+C6",
	"WUXue1e6Pt1+jerQU+CmmNOTb1bdsnoh3ayG9JjRXfWXhstAV69QpkK6XxK57icK6K1j6j6fhwo+j8Px",
	"yGLO54Eqzl11mjsKUjWvVlP9yY0P4LELuDBShooxe8dwqDKzx3ehMs0fO3KlmjlVLSEHqjiMejUqXO3q",
	"VcUeio4t0r3KTsYUynYlse3EY2LhLejVEh97ssYeBQvwg22qtD1UdCQLwGIuTdkuOoAmt2BU2+XH3iSR",
	"QIp+R/tjk43mcq4a1c0ukf3dpEzlRKALkqAfsUJ/PblEWCgapwQ9e/L02fMfjjyFxgZuw/Vv+ux+qlpj",
	"gW6TFYyqde2vWkegOP20xCxJg70tK4CJLzf9iKd8IXBCLmpFFkJmh/2dJOj9JbJfuTgz5DXygpc0iEU3",
	"vmE7FByKGPnDhks5WzKGmoQ5In6xPepgd1RpK21yLG3IZJl5hEys7vH52cQL6J2sjoALcsJwTicvJk/3",
	"D/efgn2ulsAIByYq+MVvk4WJbOCuV9hZMnkxeUsUTGy1dFCIwXECHz85PLRalbKTeJVMDv5VGjwbc2HI",
	"mPCXgT2HQpFlGb/53CzdVMq1VY5TJIlYEWENAki3cGJC78hEQnuT5fYtr773S7v3KU/IxNCNSPWKJ+vt",
	"blrP77wfjTB+bY5/+XZI15CheInZgiQaT8/CSIcqgki4LehxPwQ0XM7mKTVi6d7UOwFgLAGh3pX+/aBZ",
	"hqmTl/1xj4nX6suatzGAY/ds4W/BpDqVvj3oA/oApMESoRJU5cMz4gy5bqMHrv6pV77Xw2k7M7GF5Z9A",
	"qWl3qgJdCwucEVOW6ZeOSpWnlz/VqlXa/k9VXVb0En3ntVz47sNkdx+9z6iyFYYLwWqFfKGIqF7g7wUB",
	"34rRHSez9etyGS2FS9q2S2E25fjHR+SegUZwASZy2Q81O8h1IJPmSD4LFWhFpU8BiXaZZ4h7f7C0da2V",
	"TMZ7GMRmUoAHli2N3sGZB7+VndO+bMalrQLYY7k0UA/7+vrs1PGYvlorFvP7utXlus9vLS3hj5PxbU+G",
	"4QhIKPzKhwAj6VqgBlhfHvxWEfvLQePZr+vaC3QKHODxem/AcPc/xAVaEEZMYISLBT47bbLlHn46//Ps",
	"SXyUPCN/+eHw6ImpLxA4LLXK292npXp9+V87DqQPH5J//t9uwV8O937Ae/OPvx19/2X3nybfmkc35U+o",
	"rA9vNGGJ2JI/g7qZJyCsPfugKwHiEMpKk+6MaCu6gudBp8XtOYCc2dpjNXs2TFF591ygYQ9o84rnJ+XA",
	"Fv2fhRTWsj2AVDzPycOkgAbAr3//Jeo+rw7Oxze7mkuFWNQN2Zb5FQcm7DDBFBaqTrXtG2E+CoTayBJ7",
	"8g3oYF+LwFvwcJusnNK1+qIM5YIvIObyYeyOoauHi3f2OR8Obb3ERHVsmxdxxlfE9PCzbVBc7offiLyU",
	"llp2zrAkWrGp89IprOBXthglBLxFDIwPkwIGikAvdU8eNDFgyjO0Pqm6sOxcX/yEOEvXu/voHVmZYv9c",
	"EqhPJkzEn0CuAMA+ulpCYF6Sc8oUSjiRIMUFcf0AarjFC0yZVGXXuElAme5F6xalVblMzzGpEFSJl867",
	"ztunQfCDpVubTp6UKwIEvrFIl31YjxBhsVjnyjoHoBydZvQE3ZJ1BIlQsLKsd+lz5wFhE06BTcSEDx1R",
	"++gY+s9pacEUOr++QnxFxJ2gipjPckFWtp1xm3XbHHFetDhi+3I71Cnx67rPNmNHWbXbqMgF/Pbk8Oib",
	"wWTb0zQg6tcmvc+5QAUTBMdLSMt2QYAPVJQECUn51sVxEOMcQ10ZV38jJEBPliS+lWVFkFzQFU3Jwtlb",
	"aYpK5pVop1ROIheeof8554LEWGudu7YaTeAYoEvKFikxWUtuuVivHkG4OITiLAbk54m/pcfkXbfOuodP",
	"yjEuhDUnosLWVxSsQMMSpyUEqMYAwB765hOqkxlew88SSZIadyhcoNAZTGoZeXJ5A10eJMpxfIsXpusp",
	"Rv/z7BxhES/pikAxVDPLPCWfqeZ70xbWTKrh0pzF5/OUMoIww+laUhDMrz/HJAXrqZBKqyych+SngfLM",
	"6+7Sa62f8CzDe5LoQXpPqfUp221BBCBYb66B6QuQ7ytK7nb30fEK0xSXu5DVjxFkLsmodBdFVdcLGaFV",
	"JiMXZh/5RlrkYsz33LmJam7nyFY2ibwIKD8KcVICYNY3IaYhPxVAPOlzpW1m6v9K8/oRKp9/Z5RhWLm5",
	"QOvUeKzip/dVnKWZw16IJLFI94Tu6OPdETBXoZFagQ1LvECFKfk/pox0e1dn/lymdEV1oB8K8r3gGZYa",
	"5hhBCk1ph+h7rirImqfYPIBAZQAQIJWo77NLtDVvVCP3hDIjLF5mWNzuo2NjS+15npSCmf4KENsqVlUz",
	"5W6DRS/xpgLmEY3PapXuu+CV2x5yoYfQKQi6uRjHsnkBh5333QwlnvzExwfdDQBPNe+gJWWzPUrwTQAp",
	"qNU5EXs5pqK0gV1waPDWbuHtEe/rMTRycaUVC5e2Rw1j5zxNQ4MqN0wrTFbfdliuWVzhWTM93HMMzMtM",
	"a23l9YA0FuU+qqmaJl5C26HA/3A76glMuUFE576dUdaa0/cvQwSLlJJScIaOCxaqcV62b3TUyPDNvEWb",
	"Hdix3iJPZ4ucrQLVzPWhi4wLgQqU0owqRD7HhCRu1oBv6ZiZMgm18+68TNs498bD5B37uvRuGQdh3rZN",
	"YqWtPqCVNo4TlBG15ImR2XOCoTaIqaLhXmdMzdo9hcWCqCbjI2OaQyFLlkDWnomacmYWXhDT2wQpnvOU",
	"L9YoIYKuXIon5PNwcZvSudqzNgmcBdd0H73jlY3h+w0EQY4RA4Y5l94ZOcdUtOyN7Z+Z2jLrRwx1GZW1",
	"UIcmkLDQbQZRW9dFk7jzNJ2WnLCd10PLoObste0dn+EbVXv7nU2lgW3T7lbazNPsWZZehYqckgi0tM4j",
	"R60uW9q7UnyTujob0D8vwwwvSAZ95m6mVZgypDtCNGScwn/t7qMbv6YsZ+kawvKb/K4RLfEqyPCFx++/",
	"c5/UgOMIiIOhY7Ylg4d+jYaFwExtzX/z7PDptq0RWcznNDYFWVscFKGMSknZ4gX6pTxD+8e2EMAlJCvX",
	"k5r2SwN5/wS8WB+DyT9m1vNyoRpUv0w61po00xRbq9XyBYe7Ng1aNMeFWmqyWG6XRWxuWOiSDOcwxfGt",
	"DJH/QQIGztg6+KyiOS4nAlDIWVviVN6A7gvWad3V2HE3nK33be9Ke41qgOLKK0WrZm/16/Pd8bHrdFql",
	"K8t7Xpo1Tf+02vJja5jVUt6d+VXuyHJlWx5uxCXp4hg9lnhwzCIuPVP+rA0eBH3r4DeGM/Klz2I3ZqK5",
	"yCqdtBFyA5fszFTJ2EdXhkXdnaZxTFlBqrBJ6mqBGaVPs5FUNE3tM8uQTa9VkSHfnh5jinZg6eCsvAeg",
	"2pfPvMGgGpv3Mj747OMDDZdmPj0V77p6x5f5kWWWgMsR/HgvJ9W50ZHsHKOcEMIVWnDmTRXPclCaK3PK",
	"qFw+1Idt/BQYSfNMYLTIBjeLgnW/ZDhRSllCVzQpcOpbV8ppXPvINaFP17YogCnRkDteGpBxFwUbG6sL",
	"ji1/6g5HbckG2/PV3lO2lXbxRcE2EWw1ltmCcGvOF2CEg99sVGtXUJOJJqgRbjB6tWCoK1h1IO5usABM",
	"gICh2MqC+aEU/QEsBtrOMM2CbcnKsnEZuE6WFlW0wBo+n7Ex2RJwrFGpaOxiO+tugu+kv5xJI99HrrBZ",
	"GaDhYqOvz5Di2kKCQk6VE1vRrOw+R8Z4KuX4S0dxtCCqsZHhM/6Q22b7PlOz58DZvloKXiyWeeHvsJMp",
	"p8aSQG6fqMThg4NGVBgQzX1Vl4BguKCWJW/NkHES2zYVsEoO2omxJHuUScIkhdgQWcwMdUwGym5niPig",
	"PI/afFWWz0E7R3vQgdYUsgrz06I+f1k27Siqmv4ehdIluzMx7faNG2dBepa2dZUDyz85jCYZ/mzXt+Vh",
	"uqF5TBYH0o/NMbKsNCR0jcrgJRpsQZNPU2/1cLCnsaphQ48V6VmtsJEX8mi75AqRCH5wwThj4zpdLVda",
	"J5xcM4U/7z5MWQVIEEaM3BnK+dJopGLiaNkrlszOH6qSQPWyMYH+AS3CQLDF6E6Lr+4A72+PmJaEvITo",
	"fkrSpIwwFDaYpWwbqZd+gWX8YaKtpTLB44WeKap+3N1HN5YfYTpw0eKMRMgval9GlRinr5a2kS3/GdmK",
	"mhGK8+Ja4gUxY+w/Bc7sv+K8OF4t4LPjFURWeY49Bx2WsUUbAKpNS/I5T3lS1rsKRpZwoWrSf3zPHanW",
	"4PDUNJj0X4JzsDoXthXb17wHYTv3uga/7V3Xd8+5gwwv9oaLbe7ss+5zv70cLzj2WrE6OzWLUyUdALlW",
	"pdqywNS++53Iye1fuN72vlGG+8CFWwCAW7xwH53RDEr9K7kMUx1Kfzrzg+0eDeNnDpzu0ISbqUQCEjus",
	"u/7vBTG1sINEOK5SU4xvz8TfYkU6MV4CYRIbthJtwPMqIhgRpqgg6brvlm9iYuCAn81t30/KTLnGshvi",
	"zenpX71sj7/Z+h5/i9DfsuT533ZNHTxbNnHfj6eBL++wRAzSQtyMXWm/duWbJLkNXzi2XnWzysqjiv0R",
	"DFWRe0spajQwYU+KWuNk3U+QBmKu6i3xnJO/Ucqn/uq/6et0NFllZ4ncRMNpVSPS34cL13y9kKjxXLLN",
	"BLqK8bYf2eTRXquJZX2OkjdbAR9BBnURHyWo/7BREPayNi/jUs6LNF13UvAVTlCD0e//Qu7S4oKph6YR",
	"jb2CGxRaaUnak5lfEkWL3McPIm20/Q2cEefChtK2ruh1+UWrT6+tZw7XjMJi/wM7s/Xs9V9sCgXED5ne",
	"zISV30YIo2eHz5DbLIQD20Di/Q/dySV6D1tU2gHQVoZeK4ioRqjeY5MVqaI5FupAK917EFje8z46p6GO",
	"FA6htgnycBZCXSTDpPeTyF+T2a6BFbzz3HuaNykw9ezoaajfU0ps3KpE3z+bvjKhrA9Ux2ELNXpZGeCS",
	"d3qP/8gMn5ZuWDZ0PitjAcqDtHNiO66nxFWSYgVOvdAacwZ3u9RA/dGxmXwzNbCrbk21suLNuvVUGmPm",
	"OxlwPIfhg/GmSsjjPSxxRt7PgRT9aoejoN78sC3sjf/YnePvx0H12DgOqVoalrEy2yrPUIdBs3S4IFj7",
	"OapVWelR77TWamNfQ9rVTeR2Hjo6Jg6rZ1eCLhZE+FVjqkoJj6Oetdf6RmkMLdK5aq791S+UQRlJ/sUq",
	"DHJsHRzvCrk3mS3BalTOiBI0lq0iF8OFyobLkg0GdDxOCbKPX/PIBjXRjjJHX6Nal1+Eq10DCe5UbX1A",
	"U35D+l56l9W7NhObfxSk+6Mg3e+2IN0Qq9cK1W0k8E7KVte/O67/oyzeNy6LN/p8PHqJOh+yxjFxy8LT",
	"RsfxKUt0dx+MGzvkMU10swTUiA+905if/TSLzmraq46xB7b1WOcup2MD12br2lUDJiSBB1ZzI5s6RTZp",
	"uBpZa/01IZ/zo+1fMX9EU/wRTfGPFk3R0xSxx2gu4ylGPJZ7h/rBBUGr5a36DTJB3/2Qo1YR3cmcg5mW",
	"D3vmzWAPOuA5gRs2xF/p8cZJczN9XY5/HBPcW6xcavMIieYzeQr42eiZJPjQFbhf33tFHvQi21FEAQ0W",
	"YG1MlWTy61YANQ2993g+WOP/ZirNhfE+f/Q6/zfT2lJ9B8heYm4DDz0QCbS3jJXzmZp50QqnhdXby/dC",
	"jb6qiWY32n4yYx4VXWaNMYKm3KAF/cEmfZo259TaYCEJwrHgUoYQdvAb/P+IUFfY2NuUz7A+bQMKzRWU",
	"dZ6R1BjBGV8RqyyaIxw2A0xDyD4L4EFNSx/1sgkgqZcJADkuRGjh0DokxAxOt5OVYUN5zZQ14gxF8wHw",
	"I9TaGhdkPKHz9Tck/GMF/zlsPPR2MyzhVf4ra2v59xzawY1bECue0Vizz+7jXYJoh3HbKEeiDCfkYcH3",
	"U2AGyxzgY9R6plzSHO3gJDmwIsMxzwGw581U7lby67cBrwv0Aexlz2aX9uRegadfU8jUIXap6wGztr6z",
	"pOqBHg44qA/fngvOBSrjGS8UwmiVDcqWb0q2RwgU6mkEfl9BcTN9HA34ZrrdCF5T+qaKjvAO7oFXFrNH",
	"8zC10W+mbwTPahGIDQb5nZ/adjPoh4cMB+N/texuHI8YMxOYNFw1oEsMILuIjcIo4bo3fxiyNiGFTXsh",
	"gXadGtuMbAdzM92gE0wDDOP5vmcWwtdlq0BD6CBj1Z3MA5fBOx5o1QJs4LfY3aZzeSYIvk34XcvNrNeB",
	"T2EuQ7tCpJMXkwOc04PV0eTLxy//LwAA///do/ahByQBAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	pathPrefix := path.Dir(pathToFile)

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(pathPrefix, "https://raw.githubusercontent.com/kubev2v/migration-planner/main/api/v1alpha1/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
