// Package v2 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v2

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	externalRef0 "github.com/kubev2v/migration-planner/api/v1alpha1"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get agent status
	// (GET /agent)
	GetAgentStatus(c *gin.Context)
	// Change agent mode
	// (POST /agent)
	SetAgentMode(c *gin.Context)
	// List all collections
	// (GET /collections)
	ListCollections(c *gin.Context)
	// Compare two collections — returns aggregates and diffs
	// (GET /collections/compare/{aId}/{bId})
	CompareCollections(c *gin.Context, aId string, bId string)
	// Drill down — VM IDs that differ between two collections for a given dimension
	// (GET /collections/compare/{aId}/{bId}/{dimension})
	CompareCollectionsDiff(c *gin.Context, aId string, bId string, dimension CompareCollectionsDiffParamsDimension, params CompareCollectionsDiffParams)
	// List detected applications in a collection
	// (GET /collections/{id}/applications)
	ListApplications(c *gin.Context, id string)
	// Get latest cluster utilization by cluster ID
	// (GET /collections/{id}/clusters/{clusterId}/utilization)
	GetClusterUtilization(c *gin.Context, id string, clusterId string)
	// Export collection data as CSV ZIP archive or Excel workbook
	// (GET /collections/{id}/export)
	ExportCollection(c *gin.Context, id string, params ExportCollectionParams)
	// List all groups in a collection
	// (GET /collections/{id}/groups)
	ListGroups(c *gin.Context, id string, params ListGroupsParams)
	// Get group by ID with its VirtualMachines
	// (GET /collections/{id}/groups/{groupId})
	GetGroup(c *gin.Context, id string, groupId string, params GetGroupParams)
	// Get collected inventory for a collection
	// (GET /collections/{id}/inventory)
	GetInventory(c *gin.Context, id string)
	// List VirtualMachines in a collection
	// (GET /collections/{id}/virtualmachines)
	ListVirtualMachines(c *gin.Context, id string, params ListVirtualMachinesParams)
	// Get available filter option values
	// (GET /collections/{id}/virtualmachines/filter-options)
	GetVMFilterOptions(c *gin.Context, id string)
	// Get all distinct labels with counts
	// (GET /collections/{id}/virtualmachines/labels)
	GetVMLabels(c *gin.Context, id string)
	// Get VirtualMachine details
	// (GET /collections/{id}/virtualmachines/{vmId})
	GetVirtualMachine(c *gin.Context, id string, vmId string)
	// Get utilization breakdown for a specific VM
	// (GET /collections/{id}/virtualmachines/{vmId}/utilization)
	GetVMUtilization(c *gin.Context, id string, vmId string)
	// Stop collector
	// (DELETE /collector)
	StopCollector(c *gin.Context)
	// Get collector status
	// (GET /collector)
	GetCollectorStatus(c *gin.Context)
	// Start a collection
	// (POST /collector)
	StartCollector(c *gin.Context)
	// Start a collection from RVTools files
	// (POST /collector/rvtools)
	StartRvtoolsCollector(c *gin.Context)
	// Delete stored credentials
	// (DELETE /credentials)
	DeleteCredentials(c *gin.Context)
	// Get stored credential status
	// (GET /credentials)
	GetCredentials(c *gin.Context)
	// Store vCenter credentials
	// (PUT /credentials)
	PutCredentials(c *gin.Context)
	// Check vSphere operation capabilities
	// (GET /credentials/capabilities)
	GetCredentialCapabilities(c *gin.Context)
	// Cancel benchmark
	// (DELETE /forecaster)
	StopForecaster(c *gin.Context)
	// Poll forecaster status
	// (GET /forecaster)
	GetForecasterStatus(c *gin.Context)
	// Start benchmark
	// (POST /forecaster)
	StartForecaster(c *gin.Context)
	// Compute pair capabilities
	// (POST /forecaster/capabilities)
	PostForecasterPairCapabilities(c *gin.Context)
	// List available datastores
	// (GET /forecaster/datastores)
	GetForecasterDatastores(c *gin.Context)
	// Cancel a single pair
	// (DELETE /forecaster/pairs/{name})
	StopForecasterPair(c *gin.Context, name string)
	// List benchmark runs
	// (GET /forecaster/runs)
	GetForecasterRuns(c *gin.Context, params GetForecasterRunsParams)
	// Delete a benchmark run
	// (DELETE /forecaster/runs/{id})
	DeleteForecasterRun(c *gin.Context, id int64)
	// Get throughput statistics
	// (GET /forecaster/stats)
	GetForecasterStats(c *gin.Context, params GetForecasterStatsParams)
	// List groups from the latest collection
	// (GET /groups)
	ListLatestGroups(c *gin.Context, params ListLatestGroupsParams)
	// Create a new group in the latest collection
	// (POST /groups)
	CreateLatestGroup(c *gin.Context)
	// Delete group from the latest collection
	// (DELETE /groups/{groupId})
	DeleteLatestGroup(c *gin.Context, groupId string)
	// Get group by ID from the latest collection
	// (GET /groups/{groupId})
	GetLatestGroup(c *gin.Context, groupId string, params GetLatestGroupParams)
	// Update group in the latest collection
	// (PATCH /groups/{groupId})
	UpdateLatestGroup(c *gin.Context, groupId string)
	// Stop inspector
	// (DELETE /inspector)
	StopInspection(c *gin.Context)
	// Get inspector status
	// (GET /inspector)
	GetInspectorStatus(c *gin.Context, params GetInspectorStatusParams)
	// Start deep inspection for VMs
	// (POST /inspector)
	StartInspection(c *gin.Context)
	// Get VDDK upload status
	// (GET /inspector/vddk)
	GetInspectorVddkStatus(c *gin.Context)
	// Upload VDDK tarball
	// (PUT /inspector/vddk)
	PutInspectorVddk(c *gin.Context)
	// Get inventory from the latest collection
	// (GET /inventory)
	GetLatestInventory(c *gin.Context)
	// Get agent version information
	// (GET /version)
	GetVersion(c *gin.Context)
	// List VirtualMachines from the latest collection
	// (GET /virtualmachines)
	ListLatestVirtualMachines(c *gin.Context, params ListLatestVirtualMachinesParams)
	// Batch update migration exclusion for multiple VMs in the latest collection
	// (POST /virtualmachines/batch-update-exclusion)
	BatchUpdateLatestVMExclusion(c *gin.Context)
	// Get available filter option values from the latest collection
	// (GET /virtualmachines/filter-options)
	GetLatestVMFilterOptions(c *gin.Context)
	// Get all distinct labels with counts from the latest collection
	// (GET /virtualmachines/labels)
	GetLatestVMLabels(c *gin.Context)
	// Remove a label from all VMs in the latest collection
	// (DELETE /virtualmachines/labels/{label})
	DeleteLatestLabelGlobally(c *gin.Context, label string)
	// Add or remove a label from multiple VMs in the latest collection
	// (PATCH /virtualmachines/labels/{label})
	UpdateLatestLabelVMs(c *gin.Context, label string)
	// Get VirtualMachine details from the latest collection
	// (GET /virtualmachines/{vmId})
	GetLatestVirtualMachine(c *gin.Context, vmId string)
	// Update VirtualMachine properties in the latest collection
	// (PATCH /virtualmachines/{vmId})
	UpdateLatestVirtualMachine(c *gin.Context, vmId string)
	// Get utilization breakdown for a specific VM from the latest collection
	// (GET /virtualmachines/{vmId}/utilization)
	GetLatestVMUtilization(c *gin.Context, vmId string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetAgentStatus operation middleware
func (siw *ServerInterfaceWrapper) GetAgentStatus(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAgentStatus(c)
}

// SetAgentMode operation middleware
func (siw *ServerInterfaceWrapper) SetAgentMode(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SetAgentMode(c)
}

// ListCollections operation middleware
func (siw *ServerInterfaceWrapper) ListCollections(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListCollections(c)
}

// CompareCollections operation middleware
func (siw *ServerInterfaceWrapper) CompareCollections(c *gin.Context) {

	var err error

	// ------------- Path parameter "aId" -------------
	var aId string

	err = runtime.BindStyledParameterWithOptions("simple", "aId", c.Param("aId"), &aId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter aId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "bId" -------------
	var bId string

	err = runtime.BindStyledParameterWithOptions("simple", "bId", c.Param("bId"), &bId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter bId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CompareCollections(c, aId, bId)
}

// CompareCollectionsDiff operation middleware
func (siw *ServerInterfaceWrapper) CompareCollectionsDiff(c *gin.Context) {

	var err error

	// ------------- Path parameter "aId" -------------
	var aId string

	err = runtime.BindStyledParameterWithOptions("simple", "aId", c.Param("aId"), &aId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter aId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "bId" -------------
	var bId string

	err = runtime.BindStyledParameterWithOptions("simple", "bId", c.Param("bId"), &bId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter bId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "dimension" -------------
	var dimension CompareCollectionsDiffParamsDimension

	err = runtime.BindStyledParameterWithOptions("simple", "dimension", c.Param("dimension"), &dimension, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter dimension: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params CompareCollectionsDiffParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CompareCollectionsDiff(c, aId, bId, dimension, params)
}

// ListApplications operation middleware
func (siw *ServerInterfaceWrapper) ListApplications(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListApplications(c, id)
}

// GetClusterUtilization operation middleware
func (siw *ServerInterfaceWrapper) GetClusterUtilization(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "clusterId" -------------
	var clusterId string

	err = runtime.BindStyledParameterWithOptions("simple", "clusterId", c.Param("clusterId"), &clusterId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter clusterId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetClusterUtilization(c, id, clusterId)
}

// ExportCollection operation middleware
func (siw *ServerInterfaceWrapper) ExportCollection(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ExportCollectionParams

	// ------------- Optional query parameter "scope" -------------

	err = runtime.BindQueryParameter("form", true, false, "scope", c.Request.URL.Query(), &params.Scope)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter scope: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "format" -------------

	err = runtime.BindQueryParameter("form", true, false, "format", c.Request.URL.Query(), &params.Format)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter format: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ExportCollection(c, id, params)
}

// ListGroups operation middleware
func (siw *ServerInterfaceWrapper) ListGroups(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListGroupsParams

	// ------------- Optional query parameter "byName" -------------

	err = runtime.BindQueryParameter("form", true, false, "byName", c.Request.URL.Query(), &params.ByName)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter byName: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListGroups(c, id, params)
}

// GetGroup operation middleware
func (siw *ServerInterfaceWrapper) GetGroup(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "groupId" -------------
	var groupId string

	err = runtime.BindStyledParameterWithOptions("simple", "groupId", c.Param("groupId"), &groupId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter groupId: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetGroupParams

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", c.Request.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sort: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetGroup(c, id, groupId, params)
}

// GetInventory operation middleware
func (siw *ServerInterfaceWrapper) GetInventory(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetInventory(c, id)
}

// ListVirtualMachines operation middleware
func (siw *ServerInterfaceWrapper) ListVirtualMachines(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListVirtualMachinesParams

	// ------------- Optional query parameter "byExpression" -------------

	err = runtime.BindQueryParameter("form", true, false, "byExpression", c.Request.URL.Query(), &params.ByExpression)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter byExpression: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", c.Request.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sort: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListVirtualMachines(c, id, params)
}

// GetVMFilterOptions operation middleware
func (siw *ServerInterfaceWrapper) GetVMFilterOptions(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVMFilterOptions(c, id)
}

// GetVMLabels operation middleware
func (siw *ServerInterfaceWrapper) GetVMLabels(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVMLabels(c, id)
}

// GetVirtualMachine operation middleware
func (siw *ServerInterfaceWrapper) GetVirtualMachine(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "vmId" -------------
	var vmId string

	err = runtime.BindStyledParameterWithOptions("simple", "vmId", c.Param("vmId"), &vmId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter vmId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVirtualMachine(c, id, vmId)
}

// GetVMUtilization operation middleware
func (siw *ServerInterfaceWrapper) GetVMUtilization(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "vmId" -------------
	var vmId string

	err = runtime.BindStyledParameterWithOptions("simple", "vmId", c.Param("vmId"), &vmId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter vmId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVMUtilization(c, id, vmId)
}

// StopCollector operation middleware
func (siw *ServerInterfaceWrapper) StopCollector(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StopCollector(c)
}

// GetCollectorStatus operation middleware
func (siw *ServerInterfaceWrapper) GetCollectorStatus(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCollectorStatus(c)
}

// StartCollector operation middleware
func (siw *ServerInterfaceWrapper) StartCollector(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StartCollector(c)
}

// StartRvtoolsCollector operation middleware
func (siw *ServerInterfaceWrapper) StartRvtoolsCollector(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StartRvtoolsCollector(c)
}

// DeleteCredentials operation middleware
func (siw *ServerInterfaceWrapper) DeleteCredentials(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteCredentials(c)
}

// GetCredentials operation middleware
func (siw *ServerInterfaceWrapper) GetCredentials(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCredentials(c)
}

// PutCredentials operation middleware
func (siw *ServerInterfaceWrapper) PutCredentials(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutCredentials(c)
}

// GetCredentialCapabilities operation middleware
func (siw *ServerInterfaceWrapper) GetCredentialCapabilities(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCredentialCapabilities(c)
}

// StopForecaster operation middleware
func (siw *ServerInterfaceWrapper) StopForecaster(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StopForecaster(c)
}

// GetForecasterStatus operation middleware
func (siw *ServerInterfaceWrapper) GetForecasterStatus(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetForecasterStatus(c)
}

// StartForecaster operation middleware
func (siw *ServerInterfaceWrapper) StartForecaster(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StartForecaster(c)
}

// PostForecasterPairCapabilities operation middleware
func (siw *ServerInterfaceWrapper) PostForecasterPairCapabilities(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostForecasterPairCapabilities(c)
}

// GetForecasterDatastores operation middleware
func (siw *ServerInterfaceWrapper) GetForecasterDatastores(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetForecasterDatastores(c)
}

// StopForecasterPair operation middleware
func (siw *ServerInterfaceWrapper) StopForecasterPair(c *gin.Context) {

	var err error

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", c.Param("name"), &name, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter name: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StopForecasterPair(c, name)
}

// GetForecasterRuns operation middleware
func (siw *ServerInterfaceWrapper) GetForecasterRuns(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetForecasterRunsParams

	// ------------- Optional query parameter "pairName" -------------

	err = runtime.BindQueryParameter("form", true, false, "pairName", c.Request.URL.Query(), &params.PairName)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pairName: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetForecasterRuns(c, params)
}

// DeleteForecasterRun operation middleware
func (siw *ServerInterfaceWrapper) DeleteForecasterRun(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteForecasterRun(c, id)
}

// GetForecasterStats operation middleware
func (siw *ServerInterfaceWrapper) GetForecasterStats(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetForecasterStatsParams

	// ------------- Required query parameter "pairName" -------------

	if paramValue := c.Query("pairName"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument pairName is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "pairName", c.Request.URL.Query(), &params.PairName)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pairName: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetForecasterStats(c, params)
}

// ListLatestGroups operation middleware
func (siw *ServerInterfaceWrapper) ListLatestGroups(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListLatestGroupsParams

	// ------------- Optional query parameter "byName" -------------

	err = runtime.BindQueryParameter("form", true, false, "byName", c.Request.URL.Query(), &params.ByName)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter byName: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListLatestGroups(c, params)
}

// CreateLatestGroup operation middleware
func (siw *ServerInterfaceWrapper) CreateLatestGroup(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateLatestGroup(c)
}

// DeleteLatestGroup operation middleware
func (siw *ServerInterfaceWrapper) DeleteLatestGroup(c *gin.Context) {

	var err error

	// ------------- Path parameter "groupId" -------------
	var groupId string

	err = runtime.BindStyledParameterWithOptions("simple", "groupId", c.Param("groupId"), &groupId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter groupId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteLatestGroup(c, groupId)
}

// GetLatestGroup operation middleware
func (siw *ServerInterfaceWrapper) GetLatestGroup(c *gin.Context) {

	var err error

	// ------------- Path parameter "groupId" -------------
	var groupId string

	err = runtime.BindStyledParameterWithOptions("simple", "groupId", c.Param("groupId"), &groupId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter groupId: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetLatestGroupParams

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", c.Request.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sort: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLatestGroup(c, groupId, params)
}

// UpdateLatestGroup operation middleware
func (siw *ServerInterfaceWrapper) UpdateLatestGroup(c *gin.Context) {

	var err error

	// ------------- Path parameter "groupId" -------------
	var groupId string

	err = runtime.BindStyledParameterWithOptions("simple", "groupId", c.Param("groupId"), &groupId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter groupId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateLatestGroup(c, groupId)
}

// StopInspection operation middleware
func (siw *ServerInterfaceWrapper) StopInspection(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StopInspection(c)
}

// GetInspectorStatus operation middleware
func (siw *ServerInterfaceWrapper) GetInspectorStatus(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetInspectorStatusParams

	// ------------- Optional query parameter "includeVddk" -------------

	err = runtime.BindQueryParameter("form", true, false, "includeVddk", c.Request.URL.Query(), &params.IncludeVddk)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter includeVddk: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetInspectorStatus(c, params)
}

// StartInspection operation middleware
func (siw *ServerInterfaceWrapper) StartInspection(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StartInspection(c)
}

// GetInspectorVddkStatus operation middleware
func (siw *ServerInterfaceWrapper) GetInspectorVddkStatus(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetInspectorVddkStatus(c)
}

// PutInspectorVddk operation middleware
func (siw *ServerInterfaceWrapper) PutInspectorVddk(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutInspectorVddk(c)
}

// GetLatestInventory operation middleware
func (siw *ServerInterfaceWrapper) GetLatestInventory(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLatestInventory(c)
}

// GetVersion operation middleware
func (siw *ServerInterfaceWrapper) GetVersion(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVersion(c)
}

// ListLatestVirtualMachines operation middleware
func (siw *ServerInterfaceWrapper) ListLatestVirtualMachines(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListLatestVirtualMachinesParams

	// ------------- Optional query parameter "byExpression" -------------

	err = runtime.BindQueryParameter("form", true, false, "byExpression", c.Request.URL.Query(), &params.ByExpression)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter byExpression: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", c.Request.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sort: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListLatestVirtualMachines(c, params)
}

// BatchUpdateLatestVMExclusion operation middleware
func (siw *ServerInterfaceWrapper) BatchUpdateLatestVMExclusion(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.BatchUpdateLatestVMExclusion(c)
}

// GetLatestVMFilterOptions operation middleware
func (siw *ServerInterfaceWrapper) GetLatestVMFilterOptions(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLatestVMFilterOptions(c)
}

// GetLatestVMLabels operation middleware
func (siw *ServerInterfaceWrapper) GetLatestVMLabels(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLatestVMLabels(c)
}

// DeleteLatestLabelGlobally operation middleware
func (siw *ServerInterfaceWrapper) DeleteLatestLabelGlobally(c *gin.Context) {

	var err error

	// ------------- Path parameter "label" -------------
	var label string

	err = runtime.BindStyledParameterWithOptions("simple", "label", c.Param("label"), &label, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter label: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteLatestLabelGlobally(c, label)
}

// UpdateLatestLabelVMs operation middleware
func (siw *ServerInterfaceWrapper) UpdateLatestLabelVMs(c *gin.Context) {

	var err error

	// ------------- Path parameter "label" -------------
	var label string

	err = runtime.BindStyledParameterWithOptions("simple", "label", c.Param("label"), &label, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter label: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateLatestLabelVMs(c, label)
}

// GetLatestVirtualMachine operation middleware
func (siw *ServerInterfaceWrapper) GetLatestVirtualMachine(c *gin.Context) {

	var err error

	// ------------- Path parameter "vmId" -------------
	var vmId string

	err = runtime.BindStyledParameterWithOptions("simple", "vmId", c.Param("vmId"), &vmId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter vmId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLatestVirtualMachine(c, vmId)
}

// UpdateLatestVirtualMachine operation middleware
func (siw *ServerInterfaceWrapper) UpdateLatestVirtualMachine(c *gin.Context) {

	var err error

	// ------------- Path parameter "vmId" -------------
	var vmId string

	err = runtime.BindStyledParameterWithOptions("simple", "vmId", c.Param("vmId"), &vmId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter vmId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateLatestVirtualMachine(c, vmId)
}

// GetLatestVMUtilization operation middleware
func (siw *ServerInterfaceWrapper) GetLatestVMUtilization(c *gin.Context) {

	var err error

	// ------------- Path parameter "vmId" -------------
	var vmId string

	err = runtime.BindStyledParameterWithOptions("simple", "vmId", c.Param("vmId"), &vmId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter vmId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLatestVMUtilization(c, vmId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/agent", wrapper.GetAgentStatus)
	router.POST(options.BaseURL+"/agent", wrapper.SetAgentMode)
	router.GET(options.BaseURL+"/collections", wrapper.ListCollections)
	router.GET(options.BaseURL+"/collections/compare/:aId/:bId", wrapper.CompareCollections)
	router.GET(options.BaseURL+"/collections/compare/:aId/:bId/:dimension", wrapper.CompareCollectionsDiff)
	router.GET(options.BaseURL+"/collections/:id/applications", wrapper.ListApplications)
	router.GET(options.BaseURL+"/collections/:id/clusters/:clusterId/utilization", wrapper.GetClusterUtilization)
	router.GET(options.BaseURL+"/collections/:id/export", wrapper.ExportCollection)
	router.GET(options.BaseURL+"/collections/:id/groups", wrapper.ListGroups)
	router.GET(options.BaseURL+"/collections/:id/groups/:groupId", wrapper.GetGroup)
	router.GET(options.BaseURL+"/collections/:id/inventory", wrapper.GetInventory)
	router.GET(options.BaseURL+"/collections/:id/virtualmachines", wrapper.ListVirtualMachines)
	router.GET(options.BaseURL+"/collections/:id/virtualmachines/filter-options", wrapper.GetVMFilterOptions)
	router.GET(options.BaseURL+"/collections/:id/virtualmachines/labels", wrapper.GetVMLabels)
	router.GET(options.BaseURL+"/collections/:id/virtualmachines/:vmId", wrapper.GetVirtualMachine)
	router.GET(options.BaseURL+"/collections/:id/virtualmachines/:vmId/utilization", wrapper.GetVMUtilization)
	router.DELETE(options.BaseURL+"/collector", wrapper.StopCollector)
	router.GET(options.BaseURL+"/collector", wrapper.GetCollectorStatus)
	router.POST(options.BaseURL+"/collector", wrapper.StartCollector)
	router.POST(options.BaseURL+"/collector/rvtools", wrapper.StartRvtoolsCollector)
	router.DELETE(options.BaseURL+"/credentials", wrapper.DeleteCredentials)
	router.GET(options.BaseURL+"/credentials", wrapper.GetCredentials)
	router.PUT(options.BaseURL+"/credentials", wrapper.PutCredentials)
	router.GET(options.BaseURL+"/credentials/capabilities", wrapper.GetCredentialCapabilities)
	router.DELETE(options.BaseURL+"/forecaster", wrapper.StopForecaster)
	router.GET(options.BaseURL+"/forecaster", wrapper.GetForecasterStatus)
	router.POST(options.BaseURL+"/forecaster", wrapper.StartForecaster)
	router.POST(options.BaseURL+"/forecaster/capabilities", wrapper.PostForecasterPairCapabilities)
	router.GET(options.BaseURL+"/forecaster/datastores", wrapper.GetForecasterDatastores)
	router.DELETE(options.BaseURL+"/forecaster/pairs/:name", wrapper.StopForecasterPair)
	router.GET(options.BaseURL+"/forecaster/runs", wrapper.GetForecasterRuns)
	router.DELETE(options.BaseURL+"/forecaster/runs/:id", wrapper.DeleteForecasterRun)
	router.GET(options.BaseURL+"/forecaster/stats", wrapper.GetForecasterStats)
	router.GET(options.BaseURL+"/groups", wrapper.ListLatestGroups)
	router.POST(options.BaseURL+"/groups", wrapper.CreateLatestGroup)
	router.DELETE(options.BaseURL+"/groups/:groupId", wrapper.DeleteLatestGroup)
	router.GET(options.BaseURL+"/groups/:groupId", wrapper.GetLatestGroup)
	router.PATCH(options.BaseURL+"/groups/:groupId", wrapper.UpdateLatestGroup)
	router.DELETE(options.BaseURL+"/inspector", wrapper.StopInspection)
	router.GET(options.BaseURL+"/inspector", wrapper.GetInspectorStatus)
	router.POST(options.BaseURL+"/inspector", wrapper.StartInspection)
	router.GET(options.BaseURL+"/inspector/vddk", wrapper.GetInspectorVddkStatus)
	router.PUT(options.BaseURL+"/inspector/vddk", wrapper.PutInspectorVddk)
	router.GET(options.BaseURL+"/inventory", wrapper.GetLatestInventory)
	router.GET(options.BaseURL+"/version", wrapper.GetVersion)
	router.GET(options.BaseURL+"/virtualmachines", wrapper.ListLatestVirtualMachines)
	router.POST(options.BaseURL+"/virtualmachines/batch-update-exclusion", wrapper.BatchUpdateLatestVMExclusion)
	router.GET(options.BaseURL+"/virtualmachines/filter-options", wrapper.GetLatestVMFilterOptions)
	router.GET(options.BaseURL+"/virtualmachines/labels", wrapper.GetLatestVMLabels)
	router.DELETE(options.BaseURL+"/virtualmachines/labels/:label", wrapper.DeleteLatestLabelGlobally)
	router.PATCH(options.BaseURL+"/virtualmachines/labels/:label", wrapper.UpdateLatestLabelVMs)
	router.GET(options.BaseURL+"/virtualmachines/:vmId", wrapper.GetLatestVirtualMachine)
	router.PATCH(options.BaseURL+"/virtualmachines/:vmId", wrapper.UpdateLatestVirtualMachine)
	router.GET(options.BaseURL+"/virtualmachines/:vmId/utilization", wrapper.GetLatestVMUtilization)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+y963LbuLYg/CoofeerbdeWb7n0nM6p/mHL6cS148RlO95Ts5NJQeSShGMS4AZA2epM",
	"quYh5gnnSaZwI0ESvEiWnew++dOdRCCwblhYWDd8HUUszRgFKsXo1deRiBaQYv3H4zlQec5iuIR/5iCk",
	"+reMswy4JKBHpCwG9X+geTp69Y9RxCiFSEI8Go9iIsq/fh6P5CqD0auRkJzQ+Wg8ut9jOCN7EYthDnQP",
	"7iXHexLP9cRTQmM17NWIwz9zwiEeMwps9lsxJarM/+3bt3ExVEGiIStXZdP/hEiOvo0NUlcSy1w08YkY",
	"FSyBiZmXMNocApwzrv4Qg4g4ycyoUfkJ0iOQ/3Md+W/jkSggqM2Tcw5UIgsJisp57SfjDamtvtpbYk5x",
	"qjD5hwK5iqyhysSbtWXIaWWxOuktnCHiO3mp4nyN+RwkUj+iGeNILgBhxabt4epxXQm0j2Ptpxpu4xFf",
	"SsYS/dtriqeJQrKOweXNNWOJwQDsoAKuKWMJYDoKiug4IHNBsc2yhERY/f6OCHkJImNUQFM+cTlQ/51I",
	"SPUf/o3DbPRq9P8dlPv9wG72A2/2D0vgSwJ3alELBeYcrxrgVxbqAbmYtAFuhY51snoz9O0nxenuCfSI",
	"wJfLdMJyKpsfv8/TKXDEZujmXCCeU0roHMkFEcjDvZySUAlz4GbOjWh/c95LdYtFlRoOBbNwDy9uzptc",
	"IAGZvjlHZ6fDSX1z3kLhGgJE7Qw9MgTnCZbR4mMWYwmv76MkF4TR9tOHzLlGSQ+NQxuzmERrT0CSIQFS",
	"axmcJIqxgX2qyHgWixaSCDVJrkEcjUsWN8hUYeP6x11K6G9H45gsYVyQr3HKGTjHAUoEiQs0WqSY317m",
	"gYMt4oAlxMea0DPGUyxHr0YKzT1JwlsnJuL2ivwBb6YeBbxtEOcGqiuIqpOyfJp4M1K909QXxenaWMuI",
	"aDEFofKXF8G9RySYVcMwpSAXLA4ukWHC31vhbv7IITtdGx8BQknf2VDgBct5BKdYYiEZD0Mi9XHZM2bB",
	"WT5fZLk8P8nEIGBD+7QE36NOE8omTD4bKnJSFYoGoAV/xp48hmR5gjM8JQmRq1Zbzo2wf69bekkCkTTC",
	"1qWeP2QWj3JFtf6McYiwkLDpBISKbHMAaswqsfEnrkDZJGJ9Dp9eQZInuZrpd8Ay5yGaxlxULKQZzhM5",
	"ejXDiYBxTZX+fQFyARydXl6hnVOiJHeaK7P+Eox0oatoAXGeAN9FRDirytqHRKDIQBNU3zHX5loFitF7",
	"Rusn56uRWh7nkqXGRqiYoOUKzgj9PU+SFTo247WJd4G5JLj+r+eY5jgZjc2anwOac4FbbUlHmeVVtgAO",
	"6O0x2nlL5gt0vMQksRLQSRO0V+AUadg4CIm5FNqQUWdhzpdkqayZBRNSIDxTX2H9NzTDJMk5BAmrNjee",
	"w+kGjL4yn2qGr8fPb+2y+FGShPyBwze1iNEZiYFGAWtFaSoUsSVomMqRKAMeAZXqX3cO944OD3fHKMJJ",
	"lCeKtwgLtJxcfNy7AzJfqH9wc5jNVtOwKb4nqRKdo8NDdUhT87fDwEERZfkXvJwHTFgL4+TiI8pLdAOA",
	"bgOEFN83QTg3czwRCNmvL5sg/PpSLtx6JHkKaqSQdjMkhZTx1RNA0cmTJ4NiEFueAJr6qWX3TSk7pSCX",
	"TCxRKEk69hVE8Lwzh2pYt/jGckPhUXN+FN+jOyyQ/aSCfZdxHbqTlSAhBbgkM+KrzL47mvf5mne1XnOs",
	"mPl4PucwV5ejJtGM0hZdV+2YCEloJFExOGQm/+jkN/cxdcJ14VqO0gfzDmVowok+tNWRFAGnYjeIP2X0",
	"fNASlNG9+jJYogSwkIhRaCwYXk8yiRN1WW767tQviFZcJaTOgMCcIUkrueqtWCFmHfNxKVPdUjlhaYY5",
	"EYyektksYLqSFKgIOqGuF4CKn9EUlNkU6em0NDnbUAMcgNYjf9ASZDRZndHjvltAFYELZXEUH59s8nGN",
	"ASUBSpDK+YcS9ypPU8xXrdct55SsnahOZQhtDk6ZXHjCI/bRGY3hHh0qu/EY7UyxgIRQ2B0jon84Uj+c",
	"7PvemG5qNHXVN30CnZnPn+kDqPxL1SGnrrNGhBqbDjiJkPoVuDpVBNo5QSmhuUDHu+iOyAUSqzQFqYYJ",
	"kHtqKIpYTqVQ52QpZvuF+kMLLBBlyPLkwHJEIduuXIfLwmsq+aqpsTaYoKGSNpjDVzNrf14T6C0okPAl",
	"W8uwFYLufdHtqK9tiTVFt9dR7E/fASbjbf6TlkDXax3dSkEIZdLdqdPWBHz0rU5/0xnucvqSA45XxgjT",
	"cQ8duXFA1/6CzJ4R2gvFReVno4T1ukPDXhXEzX8vLTTBHyc+iC0jPLhrI84N7F1DzH8vCtS61rBxucCA",
	"14YIa4TjQvsoEKFJJA7coAs152u5fXTBBJFkqe4CmAp0ohVYyjjsBy0L7/ir21o5lc6iEFgSMVsV8Zfy",
	"PCYUHaNpLhFlUv3lpGOVk4escuKvctxv0Riy9VNdn8YNomf2X8PBYfWrtbmC6KrfW4JadXtNDRXtNt8Q",
	"g0/HRLTNRwRKiJAtIbGukAqznytw9tHrNJMrpPWa0TAaYbiPAGIzRmO3Pzz+EjwdRoZSI59gDtAg47R9",
	"+oazPGuNSdXimSm+fwd0LhejVy8PDzdOgmCpwjOTq3GK7397eXioEZqRxPqfU0LdMkcPz7TQoSe9grtG",
	"emi4+/m219OYHWnMwiFPi20LY/R1DCdth1nOA6K8nACVwNHHy3fmwlJMI9AUEqb0AAudZrkAHr5huymL",
	"EaGAM05Ih9/XhwJzQDqgEhdeaQ4y5xRiBfV+f5KBQtwD2K0eomIlolS/Honbs3DQbMYBJjjDEZGrNyfh",
	"mNsC8/gOcziOIkiAq0veOVv6kSvPx7xgQp4F6HNW3LiV2lGk0O7qO+0kN/raIaBMESwljhb6tKR5khir",
	"VPIcQtd1FkPSEvVjkkUsudY/fA0ZNtqtfcYmjM7IPC9Dj1123FX4K6d1++gp26BZAo2D8dO6+lO/Nhdr",
	"cLOYcexEoJ2ZNWI5qnZK2ilITJL+2N1QLT/WX2rgpwMjtArjwYMpxqewJNG6UNG2qLIVn2M1sGWD2SHn",
	"rTJqB9y08b6Ul/rR+/vVGL1X/7m5YckYMY4+XL99fdnrF/Q1W4XkBTk7uX6BCW89QNWmDiLRTsOtxMzD",
	"KPZHuoOYQgIS3uEpJG8SNsVJsupI2JrNjFnfk4AkF1iiBY616kvU3IhDypZ+qpmnI/SIsDfLfKznu8Oi",
	"OUsLScyM4xLgEOqvhSQplnCJaciunYKQEyxCETmrBJFZHe3A/nwffRodLZ4fpp9Gu6GTFO6zFtK1zfZs",
	"cfSybbY7xtcF7vniRct0NdoVeHtA+yuGSPm7Dd6r7dKesJpmStbiy5yK8GHRnlLTutV6E2FOVhLEtbsg",
	"DMhrKT76mCUM21StLeXD6Mwu37WQgTExzbLYWqU2gU97DizRtPKi6hjrcCIMzbhR1GjjQuBKDuun1FSZ",
	"7S/ZJT5KdEKSQ359+Y7dmfvDgKNPjf+YZYPHg5AXwI+ue53TVY1hHLGDk5bGoxQwXWt4TNb7gKwzunPn",
	"CKz4V1zMA9Iu41NYbpqx5UuTt5JHogr6JWolySsgjD0Z8fnv87ZL8KBVaylIhzs9A3owYGI1tIBzMLp9",
	"/7lPR/u7Mryl9NV/O5mTXWnPH/QfcILmar2+zOfSC1Cd5Xf97wjuM26y+NBOdjs/MMPR6dW7XX0YaUkZ",
	"vRrZ0P2n/PDwOfyG/v3NCcI0LlKKfkN/yTiL/zI0VPqRkn/mYDHYJFb9xuBORJbgVWvytsnDXYP0HRHu",
	"DgeDBqbbna8xHS7URpQCcuw8fz1evQ5/Xc/hYwEdt/vAWinQg/1gnAldApXMeJu7vjgrBj4KZdZL1L8h",
	"XOY4OcfRglDodTEakpgl1iW2uhq9B3nH+G3IxahuoIHrgvkAmd/1lkGEChKDvjLM9X0rtH2zgLPlAuE4",
	"VoojmN6Ao0BG0vHEfYOwQAKAoumqe2la4hjGRSMx4yztnifjMCOFi7JtMjMKJXoY2pmcnV5WkpEIlc+f",
	"hT37DRa9JUKyOcepWS5TR5S+iRgXU41j2ERQ6g6DhkunVAMpoTc4yaHNUIBswFYvJrFfjA0kIZF7y0KX",
	"8SjLJ4xDZ8bO5OIjivSgVk+bn7mT5VcsugXZO6eww4bM2nEClWdPmWuqLz4hudZn4HkgTqTI47LbCEXn",
	"JzW50deXfjjTXidOynRufJ5ljMuu9GCXT7s8ZyYhSSDhvirCKdpDuqOAv1oJCel+4Vhb7bsVz6sr7oYL",
	"YtqdS8vBIG8Man2J3X6/d+G3bPdCntEZx+1ZahfA1eUr0g79NXdvlOUflsAnLE2JTCEUiFMirsZExRh0",
	"iSVh+2hSSTfWBwc6ThKmFYxOPxboAJk43MViJXT61sTuwAF3lMJNPvzoK2+hAWQV5y7ULUEZ59anFcfE",
	"2LAXFdq2Uq7kis5IHwyYVlstMCkO2jzxsJJeRx3rrd/H08vjc6ckNmGt/dTx1v4Vm7T/BIZx1x6pw0no",
	"7IwA1iY+UMnarNOwxdoqd47osMneOl4HDbOtsS8U+zVLN4XXI2Blp4QViK60KcqiQ6aaxCQJHHVv8xTT",
	"PXVF1XmZdhzCU5ZLE4u0oX5SrIHc/bTpBl0rUwd6E3U6Mg8C4DS9bpt62oLpOnUiaz5dFGsFf74sAAj+",
	"PPGgCg8oQQ3+3pFpA12S0p5s1UL24rsGtXu9G13E9POGwKU+BX9zs6sdGce3vVekOL71NP46BPJuhLXa",
	"5KGXRVM27F0Z63f94pdOCE6tsR60Cvzit85Evdrwb0WiYa1kacAk/hf68mzNlu6LsxqkuFbaL52MM3kL",
	"3pW4c/R5k7fmmmuAC9JXiBzECQd8G7O7QEkFjpdEWDZ3xcF0Hm0lh/3YfomIWqOlYMCkua8/eZEg3z55",
	"i/7tm9no5/ZpCTXHfdBH2Df5WflxxxJ3mOv9vfb0fzcftk5dT0Z15C+XrOI3LtnfPB5KITp3de5amgIy",
	"JAQI4YyzxuEWtfuISDj4XkRRB4ZGy/XdaiE02l07S3FHZLRYLwDuwvvubBAS0xhz2yrFVdaqv7npx6Oc",
	"FlewYMhrmWDakpCwTEWrsy2cZ9La7iFU29xMRO6rlLUZUn7i1AIvAYl8NiMR0RmTnCxJApVcR+96mxIh",
	"CJ1flKMai11lEJEZiYq63HJKE0rHHJCdZ/O8RIdriFgXmPAuOm2eNNMdtXqM9Ip1I599telV2rQml6wX",
	"eAomrPRxsD16dMFZBCJg/IUDIIo8LtMts5+GNirwcN3Sjfmhd4pQ4ksI/EsyX0hB/iB0bg2TjtqG8t7W",
	"ReDmlDVbh4NSUV+CyrkGdzm0MLUGotFdRG7GfGk5H9zPrbq5WoQ+JM5eFoIPHG3rgweOtnW8Q/xERNwO",
	"jqqnawDtFTUPHD0caH25/5JxtiRK+iH+EmV5lw+iMlah/OV2uvFaxmXzJZ22OTW+RANPTk/ualLmTTN+",
	"UPmz5m9FQlvJ141rFyVDW/BKYi7LLIFWbR0xatwg0aqlv1BP/6GiB41oixtu4zgoawWPNj4bNElKX0Mr",
	"SdqrKM7ZJcxceyrrpvlB+lOFEW7Lm27IwByE+u16wUEsWFLtOfL8sN5w5B2WSmKQdOMRoSglSUIERIzG",
	"Ak1hxWiM7hYkWuiz0YZCbMUJEbr7IolBW5UGAG0/tzQpeBm8cTYBb/akKdq0NBrTnLtONOU8HkauI4m5",
	"Ojm7358tNS1oQqY9bNq65ezgA5owKjlLgi1cYt+Ga9jYthHEh9kF4Nvrou1TBYxfG9y8MF/pUiXAt6js",
	"FzWkaURnCNf4i+rlPCmhfsziaPznKfDxFnmaCp/agtUSnxZ+dHgCdU/QWiu1PCdxMKlhgxSTVn/huFj6",
	"cyvcOtv75ly0qm4cB5ssan2NYz+tWxcdbVtxl7yo62yFdWrLcYLQmZ89AGecpU8KYkhcnMuypZllb95X",
	"iJU35yZrzmTgieFdVuu1sbaJSQzSNCvGtUakYg0XwbijccpprV3KJpObxh8TLGHOeEjLeauYsSgqB2+w",
	"lN4qQ5ZJzMB1loirgcc2vhSj1iZY2E530UK3dB3XEJnH/S10b87N911dBHLanUtTOHABRwu7gXeEdi7w",
	"GDjCwtLZmD+7o7UC40kfL+3cNp6Z6PSZXMDmFE9KimrUw3RzbQQ7Ag4LP4WrM8mgGNidTKh/+p3xah+M",
	"IeP+TuTCutRF9zfvmeyevqXQOQBbLyBtq4Yp3lqdck/kqujwaM2mtgSRLja42941Ae4azXwbB+TOLeSk",
	"f7pCRYNcVMKEElhCMkZAOYkWEJtdYpIy1FpIkD90Q0AzcB9d5RlwATEIFHvLnKwmxZxeRW5JGz+Lrjus",
	"1pRae8stV1DYPzkFccSZ0Fjf7nkElAS4ULs5dpmeYIo5dBt8OifUNn27JidjdHS498z86dnh3kvzp5eH",
	"f70mJ7v7n2iIcAZz6zDZkHJvTh7wsSPWlgkeRPR6lXUnT/UtpCboWSQos+slbDXzcB64AdHO4W8fy2jU",
	"GB399hqL1Rg9++0cYpKnY/T8t7eYx2P04re/L4iENwlbwu6oH8Us72NeCL+Bm2Fy8VFvADTNdaKqKQoc",
	"o0+jw70Xn0bqDy/3/t384de9o1/Mn47+297zZ+aPz5/9tVI62IbGuXa0PSImZoF+ZEI4PN/7xf7+y8u9",
	"o2cW36Nnv+49e2mHP3v5yzBE35Oo2O3bRHO6Qu/PJqbRloeYBdUCafEx/3vRBjBpZjF0Xi5rw795rdr9",
	"836Q/7EW/A6VmXsE3EDjUf+UvwQs1mlN1Q8dEw/VNA12MHFGZ2xTpWm/DunKbGv5rBynGx9BfbbmIENz",
	"bStTDbtaYA7xKRG3YmBd+hKqGSJCz4BskGEdK7Xans3ZTo6SxanumwdVhrVIcmjvBU1Zc4krm8oEm8tH",
	"wAMZwBevz/eARiyGGE2OkRpEZuqKB2ia0zgxPt0lcOL6TAFyPWOu3135H+yj81zmun83mFcslmCbCN6S",
	"7DoR+6OHO+Y0JzIsxB3jVcda8Y/jR+suZPFo6+GqtnydKIZ0zpNChKZFBrEiljDtuaagn/iQTM+AcMLo",
	"XBdBGZ6h//u//4+R2YilU0LNTKarjkAvDg/3kV5ekUhC/AqRmfuSCISnAqjN0PVeZrolmdCgVsDbmeLo",
	"9g7zWJiGoZLY5u3/UZ1Ux82UxNSmNZOBmTkXRl4U4B49FDaWjogCxCUJTH+sph++rxWSn2aeczJ6OMfV",
	"it9qbZMeR6b6mh8VQv1Z7fNqsmqzV8XKav8BfQrSONAdO41fIpGnLgMjt60PkMR8ipNkrWyO6wWgFMto",
	"oaTApSBNEp3c5D7qS+0oxylwg6rPjHCHaq3Gk0hT/BAo1iV6O6VEoqu3x8FCXfKm/fOPZ2jeO0MrafQD",
	"XhsQocSnCl6QMNXaz66El1rivOeXDRaCV0qMmo8UeF7Krhd42vr0lX6M1qq1pjCXpczNjCShpNkMMEG/",
	"m3Mjl2u6goMvTlWIjM5OFdBWM4VjPC5ePrHO1b6HvLzyBddgu2islijbQaJMyYeQECMOIk9kS2pus/Kj",
	"O8hUG++uEv0Q6xsEmrGcepHWmji29v8JMPGjAL4Xw4xQiJ1ztpz33Gdid0www1ICV1N++nQVYs9WgkD1",
	"wKErxQrUH5tb7LrC3tWq/VoZEMRo75pwEuG3b1cEPL++acktDb5SNiTw7jYYEcYEVIeHLoYu5gyu2PJA",
	"WxWBNo2iiJ8Ei1G6qYFR8WXQ6iiT7L4MeJileI9lbw+ZZiYm5QkdINc/6Uvl3++Rko9BFXIVUNrePKk/",
	"MIIlSvE92vn/d//DGYG6ooqyyjBdX70RFMH3NQJQZL++fCQoXL5fw6FyW5n8cRZvf+ik+aTIo/Ki9a2T",
	"MCDbZYc97M5Oh7S/dDZ74ESw7UtFS/9S++VVuOjMzWuKBa2/TN+vIf5Ayz/OZmMkcpEBjSsl2d0d9XS6",
	"RolnDZgyd7diGnmGTnEAVE7QfputtdXkppZbVHkUFzqfBLakLB6WHVdeLx4jxrMFpupPhOIoAiHINIHd",
	"8LIcxAVw00UhrDL0GB25Whoa2GYKQ5pdaJfL8WxGqA0N1BwcRcH5xUeTbRg8DTJClX1RzWQZsHagkL6z",
	"kbXDb3LxUQzD7qEGd6D95/CmMaZ5aDBvwbnaNplVKe7AnNrEuGYJcEwj6H1w7nc1HBXjvRS/4Ik+Izy9",
	"wxxCnafML0h9hHamhAnEOIIZCUr0jCVxiBtFZhYyIxAH23E+NIvuDXMWTLHSsOjf0YernmZUetj7cEcq",
	"N8MsT5JWAZl7vXvWaAfld/xp6WcQqPC++u/ENM7oJI0a0YWS+r0NnXU6qzQVwcDr23ri7qdJqxua2NqN",
	"LDu2PY9aCJVxkmK+Qt3dkcyVbcO93Bo9+ZPf50JNd86LfjspzLFxxw3S8V13uvJu1RDXCFM0BXu5atF6",
	"P8pt7tRrjOcMwjavgN9vS0iI3970ngVmoDtenSHbcyJQEm0q9u/PJsHCxCKq0/EYhhrjLKwNzFSd4K1M",
	"rlDm4zsiTO65G1KmdLrGRdU91oWyKwAMdq/UKfYfRYgpLv8+YlTkKeiChtBuaPFwtN/oO/ZC/41eMpYI",
	"2yCi1LnhBewZfK0+UVOXHUICfXRZItrmq85DhcRJggsLOw+q43x4w4Wb1KsFPLW9W9QUecsxuAQudIQu",
	"bxyJWAgypyYzquMQfJIbX0fTS/8m5u225vXGs8UblxBPiTtL1mqDIfcy182wei+7JTTU19v0NjSGZRRz",
	"lo7RLGFZthqjXEzHSAAnOBmjDHOcJJCE76V9MFlPSC0eFJLIk1xYaEQkyFhJwBgJLPEY0WXacoWzDfNb",
	"nC3u5zW3+YwkwRT+078h9RPKsFy4pxkDlToleLewarX5dDzhFlY6EG0naxw7Q07oohSqgb5+g3vHueGp",
	"NK/8afVN5Ze2f6eMlj8Fqc7jtEsDEmF03iW+Q1bKznGWVbSU/xK2Tm/oVqmaWES4VIgpyDsAitI8kSRL",
	"6oQTA5++bjOGbQwklKugU85X3Q0uakfOgnGbu+2UWpGvYCMn4QaKutlUf/2FGzguoXOwfF4DZ3cB6HF2",
	"C1R+YsM6ovmAog0IbWq4NxgRSmTvwyzc1sTnoCv2m5QtVf5etFQ5q7RUOS5bqry2/b4+KOEc2CwqAJqt",
	"Xlh5i3eMKuHqGFQFuWOgh03HKIdoxxBLg74u3Ob8h9jvv23ybyJGJdxL3R+bQ8TSFGiM3cOQG2yxwU9v",
	"eJvFn6x/y3T3rv4Xem2utq+LlAilmGy5ZPD1uZqqfaSez8umRl+n73PzThTohhZDIEry/mxiH8PtOpgD",
	"53BPJ+eNmjZ3OKP6VaCppmytolzHDbLDIUtwBOq+rcuR5vaX3ccvXqRMThNMb0MOj7ALIWhFMOcqKLwH",
	"fR6DjXIAg2wJXYZC9fmP3d/EJGb82RuirIXlY3ZQSVlLr5thTVU2b6eyXiOVlo47dTuTmXhj6nqnBFqb",
	"tDU1CWHS13HFk9e+9ise00O9WD63lAnVy4kaO1KfOHrUyaCssOuT0l8sTVRkSKQ67U1dujkvn4WVJHgw",
	"h9LALejlEp87CqYehQr6B9u6bnukaMmT14tp/w4RbtEeMrkFxxUsP3fWRwSqhlueFjCFWK7cqPYyzZXr",
	"3G6qhTLg6BJi9BZL9LfJFcJckigB9OLZ8xcvfz3yepPYnGXtOTa92b+UDQh1o+A0p0SuKv+qblQEJ18W",
	"mMZJ+A2fAmCIw8+J5tmc4xguK3Z6oHW3+x1i9OEK2a9cYhfy2iWqn00atgkX2KGx7uOA/GG9Zr3r4hRq",
	"xVg8Qm87gWrsiNRv9RwLm6JYFN0gkwR7fHE28jJlR8tnWgoyoDgjo1ej5/uH+8+1GSoXWhAOdGMLnd1r",
	"kgmY68h4Fo9ejd6A1BNfOe8qt3cI/fGzw0NrAkg7iVfQfvCfwtDZmNJ9hra/jMY5lOMrilDdS7N0PWAs",
	"gVOcIAF8Cdw2udaVBk5NKIwQ9icbj4xp9A+zhr4XZjbaWiXGlSWGbuNjGAlCnrB4tV0qqPmL9lJVkZE8",
	"h2/fjwu6KVG0wHQOseLCizAX9BPDiJcdsl4c/hpMj5klxOipjdk50cBYjqaGMXV+fhuPDiL7+r6taAsK",
	"u7ojT7xxj0jncpnKxTxAcheA8hF4CMH0fDhJKhOWNPPxb1BOY4I5HHzFZ/G3g6/Ts/hbKzXNK/dQJWiG",
	"OU7BNOf4R8OVjgUkOg5bfIN0XIJQXY8kFy5s8WqE9VPE1Y0x9ojf0LtN6XOP8CPTbnTIqtM1V/38JCJU",
	"olJUfzflyMPXCoPxZWXA9zzM8XzOYa6sUu3dislsJswOfhFIPyHmwfLyc8qkSVV/2KY2ooPkHfPFVNc6",
	"uUKtIKAPkOODrzFJgapzcx2ZPiWz2X89uR4Hq5NAchIpK8iSN7xWQebOFZ3Z6NxnqV8TShndS0PtSNoB",
	"vCh9mGjnaG+KBcS7++hYbT8dUC8iSclKocBosjqjx1q2zJ9P9h0+/8xBe2AtQtazV8JeZIMceT3pjkJW",
	"fdeFQSdXKvtau1/VHwSJoQMGmx1bwtG59lOrJr1RAnrpAs8J1a/fWJS1aa22M/AiYiYXTWXgUs7mZAkU",
	"lVLVZ5YUI9FSP4321MrtlJMkQTG7o1qfdWEdwBg38B2q876S+NtBvW1Zqx107A/s0W+TfgVDfpxz08Ns",
	"qO0V6uLWfipOti0xGowgDIhQhD0Z8Y3fSmuxsDS43mUHX+2f1DlYS5dpuxYGemc/uZg09KerizW9cN0j",
	"7TFLMaF70dGz559Gu4hxNAcKOsWvaJvXBlFBmE7AytTJ/7njVvv0Kf7r/7Kf7/3jcO9XvDf7/PXol2+7",
	"/xbwCzymxHc0bg8ZipYi9QKW8hVOWyhZvO2EeLkAMm3Ye7Vw2d4aWQ/bOttpjCjz19drjhVnizaIW9l5",
	"b0AW2AbIMl1V5cftPY/gbVsP7jWZ2jbYa/3zxN/Y33tvTVia4j0BCg5FdIMBEhHLwGsXxJbAlwTuxstU",
	"jE2d8KfR7j46NUaR7idajvo0arOq9LyjtSD8kMssl1aeXqE/SIZ2Jlc3OvvJqsr/cXaBMI8WZAlaEdwn",
	"4h7tvL6PIEF3jN9OGbs19yLTwgRAGtNLQbPbAqoV4KAJOPqDZJ4X1PxNrRqyWtdTAksa77MM6H2aGAjE",
	"HpvNSAQxi/IUqNwXGQccayzSZF//v6o1Cuf2lFCsUWr6K/0l/zBPBa8zQUO/eCzQiRSY6IeESkYxjqoM",
	"6VUmRlae7Dw2m9O3DLV+xEIj4ePXRGUta62sw2+10964x7y/t3qwr83bzgBTm5i+E2EBe4QKZaxKot/k",
	"mZpJTOpG256artzrMMNBqN3xdDqEyfh+smubRd9d29a5rRXLPztsbWz+1Be55rP3HVaylda+zWqSdNTx",
	"wUGUN7YnM6Rxkjg2tVvPdlt17suDr/r/XT7QN2A26A+wPzUcrbNbTB62xJXSijMCSWwbDseEW6wK80Ct",
	"9wqLyLTZs9bTKzWPthJurIjoOTA3XQrGyC8RHjubS9fQ6nD42D6VO7bdMsYoyvKPAs/BjLF/5Di1f4qy",
	"/Hg5158dL+fKBIF73UzA6+isoLQE0vCpAxvus0QnLtsHaEN2izLrfLINb4ki5Cpx9sSoW73NmFYwtnvV",
	"U2o4jc5GCu77arEuDWb2hnuDV4tuPTV7gI5i9vTb4t3DzDddobNTAxaRIpQ1PkhrVV5EaFNXZ96bB38i",
	"p4//yEMgNKJR0W7gYtggfhfjt8jzqAmN9fwFTyqHmX4YL8x4m5SaermvrfZkU7h+EMNyuvJNhjaj8bU/",
	"5OfR9fPo+hc/ujqS+Dss8eDh1Z+pgbyt/rQ2eT2rv90wr6M2TOUdmEvHHsu6Ix9vQNZegPlzHYNtz9sE",
	"ZMmqXUexJ5MHnZ+1xCQxfdV8KEzATjxcGsoagnYpKN5t+VOxv/aaTEiHmNIJW+ekH1h5Wt4nOjG38naM",
	"D8yDmf91mfZc2RtlM9/bBGr0xQwvoxD7cWQt1HwrIG813OKy6H6A/V1vabg1KWyBakvCNzTGenP+Y4VX",
	"a1RxL47+K0hjsLFDQBrPq3HP4dJYyJ6Sy0D/v0pPnoeKZyUI6R4MsLdE4d6p131JBskrs5n+CZgmIbW0",
	"Z8mySTGwwaR2sjD9Mn+WwcP2o1ofRR4AtQgKM7W8rYkKbtTj57DXl2r3NTC+rVz2qD5hG31actol5rKD",
	"u8++A3FsOxddD/HwJPMytTXhgGPdVSPjbM5tJ54HyCXmsu2e4tO+stMO+FJ3uNFpI+0suTSjqpxpqzcw",
	"DSUwlwfq/r2n241W+FIt/tFh1sr9vjeM21P2bGYM1670FS/8qBL2ntl4tHud4YlkTI0+CtQn3ZimR7o7",
	"ChH6vHG9uPrk0qTuuBkMszpEtfruSXks1AumUrYEoQ123UomLtoTeTOUWUNKKqdYwP5oXBP4U72C/9zK",
	"oEPGW8TA+MC8TD2HQyWqQFOQyvtX78ypE8ZkqDdmQilIrG2BnY+X73Ra8e4+eg9LEw5lAvRbety0dOPI",
	"PVaxj64XuvNanDFCJYoZGP5z0EoQS6iQHM8xoUK6VyKaBFenYhe1t3giFst07MmSQOWZGDS33rMKnobA",
	"Dz5Bm3xqnqQ1vhfPlldsR8sL0cWMMQIa8VUmCz+zuDXZ6OgWVmOdb64BEq5VU8IinBS7B2HTcRdHOpvC",
	"BxrkPjrW+RXqoKASXXy8RmwJ/I4TBZX6LOOwJCwXySog6E1BucgbgrL9mrfAc0tPXPW2npQK5HZdXLJL",
	"i+Ezo7i/C0wRhwBE3TmY3ueMo5xywNFC+91cw7oH2u0cQmdC68aqnT4HEc6wfjGJVKJWNSIsILoVxZM4",
	"GSdLksAcbL58kqBCpgXaKeywsXsLRP1xxjhEWEjgu/adpcDuQFeEzhNAidp4brlIrW7SUfXVat6jbSc+",
	"So8p0m6dVYf4FGOsxtOxkQL4J1TDmocFTQsIUFSlVrvUlAzsMlnUTdLoQdt/Ek2BRosU89t9dGxMtz0v",
	"rTinJpKXcdDAx377vLAto5b4vQTmEa3dcpV2Dp849FCEaQQJxLpBom5uZwrpTNm6xryL3wWd/OadD+K4",
	"hqec1+OuR75eG8u+Kl4gZbrAFoWNGSa8MMSdNye4QxvUfMS9OYRzrvdWKdjbcBhcsCQJTNlK+yzYdVxf",
	"MATCYkWjkoNqOymNy6g2XlOl/Is2k0hxQoS2C+aytl+2b2HUVlmrtv57bdihDhBPE4+dYaJf31bsH5tr",
	"BOEoISmRCO4jgK6r7DFluuqtst/dpXYb+95cTnu3fVWnNwyBsFxOWJrlytK9W5BogdhsljAcq1vXgtmc",
	"jBlg/bKGltTCU2peXt2z9bI1oUXGOtfPMdJYfWYboDhLC88BabcIkixjCZuvUAycLF13b92ZjvHbhMzk",
	"XiC7J2B2M+GJ6wUmvGE2bH+TVJZZPWL/iWGtsivQBBxQ7dYMAZfkQXjr9jktmLy9kvVcGpFpM1u6JLwQ",
	"unZD15155dBh8mXfjLWSaoVYCW9U2n+kbMJZFd73x8fIPHni9bbuO0JPS2SeQlaK5VyUsV9YisrOEtIO",
	"P6DfH8GlJmwhEb3Icoh9eg2RFq2YDr5SnMK3LoPXWFnG5C1Vei1OpEXWFmzso2sjTc5CUJwiNIfC6kNk",
	"hswZYbSj0qpCkiSxLok+k1ht7L5Qphpj6kewcHCWxrc+GQvHfzD2aHu9PST2uN65X2+nSvj7cHu68Ui4",
	"1wyKzljWNA/2MQh51APEKuYYZMNbVpbWQRm8PChO+xmhRCweerEzZj5GwtydM8P9ITKubl+9upDQmCxJ",
	"nOPEN1mku+/vI5PppFv0m1wi05A/cxLWo8ku8/4UMJsppW+L/tStCYZWOB4zFj5IbxbG5mVO11GaFUHa",
	"Qjei2nzDxUPnWHSFro1Pv8LOPm5e5hvnT/T26A+wNbBVFQReQKM7/Gmgbdv1aqotda0w0RFcZdZAXimV",
	"17+XI2NCxfpWSoQkkWt5UbXI/yJ8IEwz9310YZ9mKqIkrj/IxzMkGYrtczlF41wkSQoIhCQpljDEKSCG",
	"H1uSoTnIGiL9+uDHyJVxWBucA3rgesFZPl9kuY9hq6ieE6E9qg7PMsv4wZEbGQSkQyYHFNS+0+X+w8pq",
	"f9a8/qx53XLN6/t6y5+t5NdbFjU7eHSVvralDE10pMnbJ4/kkDDr2OK9NbwRR9sVhfaCQRtyWy9H6Sl4",
	"biiHMKJwZ2sIXTB5CONLTVktce62sqoC0ak3t1+LPMiwcmWenmnVz40tV3VaO8pMue5+bEtx/K6k/1lL",
	"97OW7r98GfjjKo16Kfja57iyOpuaw7y08v319vZNB4PZ+qbD4VOZDrkGcOumw5blzpBxQwuiSK/pqy0o",
	"H04bPWoHAAtOe/C1GOKXLQTJXo7UaZhlXDQYVL3U7elc00H9ju7WUtBZVuYxVboCuH/rshvqNOnZ/mfU",
	"vER0c3r6tzKX1cqFY1zLUUDMtzdxfBu64JYPHn7+cWSgzEV9UqYqbU/qYLSxtqOEoLavHimtwn+L8buk",
	"VQxn6gZ1JWiHMnRzLnSGn5J7k+pX5lzstgpIKUnbz5+IAYp9r/P7GVdQtkhJRRsfLNUW7OwAY0eqvfr4",
	"yVBqlYsyehaqyfPVTddJqAfmWcJwvIW0cG+23k2YB0h5kVdJue0KnqH9G+t1OhuW6Tw5x31Gdm5VNbp1",
	"F340DGypy3lx9Lz5ye8kASQZQwnmc0A7Kb5Hv7w4P9l9oC2lAdGoScynOEk6t+uAXk3Gcvc7Nv34/ZOa",
	"Butj9FDyOicNuSo1eygVLyh1FGfbIY+5U8wS+gmv0DYxP/vJO62PHS0DY73qYIuLRX6NflFGBtfsGvWz",
	"pdNPN9TPlk4/Skunxwk51Vs6DVLE4S4F9SYaUyyjxZ5xoezp53Gdrg7fhk7UeN/ZdXP+uvjqca5G3pLF",
	"Uut7omoPkriJHst79HDOa7QteF6qRcEjrSmMrZtA+T7oNoRieIcvJwP1Pl//Ql23ts64/q5b29zA/f23",
	"HI+KLlz/Kj2xHocz3T2xts+ag6/6/4OjvppAbxKmbjW9nWP14EqGZDWOoJf+YbKhHJoegr2igrjujbCW",
	"gt5YQEwfBoSNYBhZUAKzsXYdFC/SeBqX0/dg9mOFjBxaDz2rDdo/7Dl9HOs2VTwgOo9zOvc33QtdJPuE",
	"62dfvA6/yhP3xtv0EBqkbX4gsXiE/hcVcA3aD9U/NRI8Xrj5UaTMxp1rc5cu8G3rpaH9GJ1VukZXxp8t",
	"E3tF6AdpljhMgdWedlOL6dUN73OejF6NDnBGDpbPRoo99ruvHc/Z61pM3dYrxRTPIVWsK2TCPGIeeo6t",
	"8vqU7g0U+n5SeTc8sPGto9yrcSz7pTSm0Q3Kvvb7/xEHU1TtTeF72Vt7iyK7NdE/c1AjEY44E6bLmPW7",
	"elM2vWI9+8+ksoTo9MZlcjcqhQMPb3qBjpJR1bdBG/kCjTcSDeOtf/eguo3KaX2BCwEHmZJdLxackBlE",
	"qygBPb0JngbwLSNOgWc0Gz17wqLld2wah0U8HHdw7LNhh2+fv/2/AAAA//8vkK1WhhwBAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	pathPrefix := path.Dir(pathToFile)

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(pathPrefix, "https://raw.githubusercontent.com/kubev2v/migration-planner/main/api/v1alpha1/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
